### ISSUE TITLE
The amount of data

### ISSUE THREAD

**Issue by lPoloBlash** [jdm-contrib/jdm#1011]
Hello, I speak as a representative of a group of student from the Universidad Complutense de Madrid (UCM), Spain.

Our objective is to make people aware of what kind of data some web services collect. Instead of starting from 0, we created a fork of Just Get My Data proyect that it's available at [repo](https://github.com/JustWhatsTheData/justwhatsthedata.github.io), or [justwhatsthedata.github.io/](https://justwhatsthedata.github.io/)

We wanted to ask the project if you could give us a few pointers and a bit of advice as you did with jgmd proyect, and if you would accept a Pull Request with a button to our project, Just What's The Data.

**Comment by tupaschoal** [comment]
Hello @lPoloBlash 

Just Get My Data is not a repository we maintain, it was just a repo based on our own, to which they asked our "blessing" and opinions, so not sure your question is really targeted at us (?)

**Comment by lPoloBlash** [comment]
I mean we inspired by their project, so as we have similar projects we wondered if you would accept a Pull Request with a button to our project.

**Comment by PyroSamurai** [comment]
HMM if you were inspired by their project and not ours, shouldn't it be their project that you want to put a button on?
You don't really have any relation to us?
