### ISSUE TITLE
Hoop (hoop.photo)

### ISSUE THREAD

**Issue by MoaufmKlo** [jdm-contrib/jdm#1044]
## Backstory

Hoop is an app where you can find friends on Snapchat, sort of like Tinder.

You get diamonds for watching ads, inviting friends, …, and can spend them by swiping on people. A couple of my friends had it, so I tried it out as well, but decided to delete my account.

I noticed that when deleting your account, it says that the app will exit once the account is deleted. Their privacy policy says the data will be stored until the user prompts deletion. After doing some testing, I noticed that the app does exit… but your data isn't deleted. People you swiped on can still see you, your diamonds are kept, …

Thus, it's possible to delete your account, but they don't actually delete your data. Just your photos and birthdate. This is contrary to what their privacy policy states, so maybe worth noting below.

Their support team is also to no use and ignored my questions.

## Data

- `name`: Hoop
- `url`:
- `url_CODE`: 
- `difficulty`: impossible
- `notes`: Account > gear icon > delete account > delete; this only removes some of your account data, not all. There is no way to remove the other data.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: hoop.photo

**Comment by tupaschoal** [comment]
Thanks for reporting, I've opened #1046 to incorporate your suggestion :)
