### ISSUE TITLE
3daimtrainer.com

### ISSUE THREAD

**Issue by kolva3** [jdm-contrib/jdm#1051]
## Backstory
was trying to delete a old account

## Data

- `name`: 3D Aim Trainer
- `url`: https://www.3daimtrainer.com/faq
- `difficulty`: hard
- `notes`: Requires an email and username
- `email`: shoot@3daimtrainer.com
- `domains`: https://www.3daimtrainer.com

**Comment by tupaschoal** [comment]
This has been added, thanks for the contribution!
