### ISSUE TITLE
logitech.com

### ISSUE THREAD

**Issue by kolva3** [jdm-contrib/jdm#1053]
## Backstory
clearing out data

## Data

- `name`: Logitech
- `url`: https://support.logi.com/hc/en-us/requests/new
- `difficulty`:
    - `hard`: Sites that require you to contact customer services or those that don't allow automatic or easy account deletion
- `notes`: Requires a country, reason, and name
- `domains`: https://www.logitech.com

**Comment by tupaschoal** [comment]
This has been added, thanks for the contribution!

**Comment by kolva3** [comment]
now they want a phone number too

**Comment by SvicidalBug** [comment]
> they also want a phone number too

Did they state why? It looks like a phone number is optional for a Logitech account, so I can't imagine why they would ask for one for deletion. Maybe you could get away with using one of those disposable phone number sites.

**Comment by kolva3** [comment]
It seems like telling them that "I would prefer if I didn't need to give a phone number" works and they ask for the country, full name, and email address again.

> > they also want a phone number too
> 
> Did they state why? It looks like a phone number is optional for a Logitech account, so I can't imagine why they would ask for one for deletion. Maybe you could get away with using one of those disposable phone number sites.
