### ISSUE TITLE
ifixit

### ISSUE THREAD

**Issue by kolva3** [jdm-contrib/jdm#1065]
## Backstory
none

## Data

- `name`: iFixit
- `url`: https://forms.obsecom.eu/requests/654931-678694-057240-634891
- `difficulty`: 
    - `hard`: Sites that require you to contact customer services or those that don't allow automatic or easy account deletion
- `domains`: ifixit.com

**Comment by tupaschoal** [comment]
Thanks for submitting @kolva3 , how is this URL related to `ifixit`? Sounds a bit unrelated.

**Comment by SvicidalBug** [comment]
> Thanks for submitting @kolva3 , how is this URL related to `ifixit`? Sounds a bit unrelated.

[It's linked in their privacy policy.](https://www.ifixit.com/Info/Privacy#Section__Your_Rights_and_Choices) Obsecom appears to be a third-party Data Protection Officer used by iFixit.

**Comment by tupaschoal** [comment]
I see, thanks!
