### ISSUE TITLE
Firefox's delete score must be HARD or IMPOSSIBLE

### ISSUE THREAD

**Issue by firefoxhistory** [jdm-contrib/jdm#1069]
## Backstory

- https://github.com/mozilla/fxa/issues/12372
- https://support.mozilla.org/en-US/questions/1372988

The old user who changed their email address at least once cannot delete their account at all. Also confirmed this on my account as well.

## Data

- `name`: 
- `url`: 
- `url_CODE`: 
- `difficulty`: 

- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by SvicidalBug** [comment]
I can't replicate. Firefox allowed me to delete my account regardless of whether I've changed my email or not.
