### ISSUE TITLE
adding these sites:

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [jdm-contrib/jdm#1074]
codeberg.org

nextcloud.com

codeproject.com

replit.com

bugs.kde.org

yourworldoftext.com

routinehub.com

macstories

telegram

signal

microsoft

imgflip.com

if i repeated you can ignore.

**Comment by tupaschoal** [comment]
@hacknorris-aka-penguin please open one issue for each, filling up the template we provide and adding the instructions and or details. We rely on users contributing their experience, but we don't take suggestions on sites to investigate and report how to delete.
