### ISSUE TITLE
Tenor

### ISSUE THREAD

**Issue by kolva3** [jdm-contrib/jdm#1075]
## Data
- `name`: Tenor
- `url`: https://support.google.com/tenor/answer/10455265?hl=en#zippy=%2Chow-can-i-terminate-my-tenor-account
- `difficulty`:
   - `hard`: Sites that require you to contact customer services or those that don't allow automatic or easy account deletion
- `notes`: requires "(a) Tenor username or (b) email address"
- `email`: support@tenor.com
- `email_subject`: 
- `email_body`: 
- `domains`: tenor.com

**Comment by tupaschoal** [comment]
@kolva3 can you add details on why it's impossible? The link says that it technically is

**Comment by kolva3** [comment]
my bad I thought impossible was that your account would never be fully deleted

**Comment by tupaschoal** [comment]
@kolva3 it depends. If what they are keeping are anonymized data to comply with local regulations, that seems fine, but when the account deactivation is not permanent (such as asking to login will trigger it to be reactivated) then you're right.

**Comment by kolva3** [comment]
![image](https://user-images.githubusercontent.com/83851584/163653567-3d9a1e18-28d0-46c8-b476-0e1035ec5141.png)
it seems like they terminate it, not sure what that means

**Comment by tupaschoal** [comment]
Added it as hard then, thanks for submitting the details @kolva3
