### ISSUE TITLE
add cTrader

### ISSUE THREAD

**Issue by sinagun** [jdm-contrib/jdm#1077]
## Backstory
so I was just deleting some old accounts that I was not using and cTrader comes up so I just first googled the deleting process and I got `https://help.ctrader.com/ctrader-id/delete` but at end of the page it says you need to contact customer services I did contact the email `community@spotware.com` but 2 day passed so idk maybe just need to wait

`fun fact`:
more than 80% of forex trader's websites you need to contact customer services to delete accounts even if you just use the demo services and did not put money in the account

## Data

- `name`: ctrader
- `url`: https://help.ctrader.com/ctrader-id/delete

- `difficulty`:`hard`
- `notes`: ctrader is a forex trader

**Comment by tupaschoal** [comment]
2 days seems too short notice, most of the time we wait for 1-2 weeks before telling that it doesn't work

**Comment by tupaschoal** [comment]
@sinagun did you hear anything back from them since then?

**Comment by tupaschoal** [comment]
Will close for lack of response, please do reopen if you have an answer

**Comment by sinagun** [comment]
@tupaschoal  I did but they want me to verify my identity to delete the account but I never did KYC
 they want a passport so it is not worth to even deleting the account any more they just have my email only

**Comment by tupaschoal** [comment]
Thanks for the feedback @sinagun . I will add it as hard and detail that it is incredibly bureaucratic then. Thanks!
