### ISSUE TITLE
Chess.com

### ISSUE THREAD

**Issue by Roxiun** [jdm-contrib/jdm#1084]
## Backstory

Now it is possible to be deleted

Relatively easy is just found under the account settings.

**Comment by GitFincy** [comment]
Saw this too recently, wanted to make a Pull Request for it as well, but i'm waiting for my Duolingo PR to come through first. Just to see how things work in this repository...

Here are the steps I documented for myself:
```
Log in
Settings
Account / Payment
Manage Account (https://www.chess.com/settings/manage-account)
Close My Account
```

**Comment by SvicidalBug** [comment]
It sounds like closing your account doesn't actually delete any of your data. The "[My Data](https://www.chess.com/my-data)" page on Chess.com has a "Right To Be Forgotten" section that allows you to permanently close and delete your account.

> To block Chess.com from using your data in the future (for example, displaying your member profile, or to display the game archives of your opponents), then you must permanently close and delete your account. This will delete your personal data, anonymize shared data (such as games and comments), and block your email address and social accounts from being used on Chess.com in the future. Certain anti-fraud data will remain, and generally this auto-expires after 30 or 90 days. This will NOT delete your comments or other public posts; if you wish those to be removed, you must delete them separately BEFORE you permanently delete your account. After you delete your account, Support Staff will have no means to verify your identity, and cannot remove these posts for you.

**Comment by tupaschoal** [comment]
@GitFincy or @SvicidalBug, did any of you test and would be willing to do a PR, then?

**Comment by SvicidalBug** [comment]
> @GitFincy or @SvicidalBug, did any of you test and would be willing to do a PR, then?

Sure, I'll make a PR.
