### ISSUE TITLE
odysee

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [jdm-contrib/jdm#1085]
## Data

- `name`: Odysee
- `url`: https://lbry.com/faq/how-to-remove-account
- `difficulty`: 
    - `hard`: Sites that require you to contact customer services or those that don't allow automatic or easy account deletion
- `notes`: 
- `email`: [hello@lbry.com](mailto:hello@lbry.com)
- `email_subject`: 
- `email_body`: 
- `domains`: odysee.com

**Comment by SvicidalBug** [comment]
An entry for LBRY already exists. Maybe it's name could be changed to `LBRY / Odysee`.

**Comment by tupaschoal** [comment]
> An entry for LBRY already exists. Maybe it's name could be changed to `LBRY / Odysee`.

Yeah, that sounds fair enough. Adding the domain and the other name.
