### ISSUE TITLE
kongregate

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [jdm-contrib/jdm#1091]
## Data

- [ ] `url`: https://kong.zendesk.com/hc/en-us/articles/360049211251-How-to-delete-your-account
- [ ] `difficulty`: easy
- [ ] `notes`: Navigate to your Kongregate profile, click on the gear, then click Delete Account

**Comment by SvicidalBug** [comment]
Added this in with #1089. I bumped the difficulty to medium as they do require you to verify your email before they will delete your account.
