### ISSUE TITLE
Hypixel Forums

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [jdm-contrib/jdm#1094]
## Data

- `name`: Hypixel Forums
- `url`: (https://hypixel.net/data-request)
- `url_CODE`: 
- `difficulty`: 
    - `hard`: Sites that require you to contact customer services or those that don't allow automatic or easy account deletion
- `notes`: requires an extreme amount of PII 
![image](https://user-images.githubusercontent.com/104040739/166153184-2f9766f5-57ff-41c2-9d2e-7f03531417e9.png)
- `email`: 
- `email_subject`: GDPR Request
- `email_body`: 
- `domains`: hypixel.net

**Comment by SvicidalBug** [comment]
Name, address, _and_ government-issued ID for a... Minecraft server. That's absolutely crazy. They don't even collect any of that information, what do they plan to "confirm" it against?
> If you wish to cancel or delete your account, you can do so by accessing our platform or contacting us for assistance with the process. Our email is included at the end of the privacy policy.

Of course, there is no email included anywhere in their privacy policy.
> We do not knowingly collect information for any child under the age of 13. If you are a child under the age of 13, you are not allowed to register nor participate on the Hypixel Forums.

I wonder if it would be easier to just tell them you're under the age of 13 and request account deletion...
