### ISSUE TITLE
Add Wappalyzer

### ISSUE THREAD

**Issue by mbtrs** [jdm-contrib/jdm#1166]
## Backstory

Click on e-mail on top right -> [Go to Account](https://www.wappalyzer.com/account/) -> Scroll down to find the delete account button in red

## Data

- `name`: Wappalyzer 
- `difficulty`: Easy

**Comment by mbtrs** [comment]
https://user-images.githubusercontent.com/40812568/172260833-eceb0e82-661c-435b-a6ac-6da69765165a.mov

**Comment by tupaschoal** [comment]
Thanks for providing details (with video!), and the PR :)
