### ISSUE TITLE
Add Kijiji.ca

### ISSUE THREAD

**Issue by mbtrs** [jdm-contrib/jdm#1169]
## Data

- `name`: Kijiji 
- `url`: https://help.kijiji.ca/helpdesk/contact-us-step/other 
- `url_CODE`: 
- `difficulty`: Hard 

- `notes`: Must contact customer service as the option to delete your own account is not possible. Once you go through the contact us form linked above, you will then get a response from customer service to the e-mail that was provided during the process. As per customer service once they have responded back to you: "We will need you to reply to this email confirming that the account (your e-mail that you entered in the contact us form) should be closed. Once you respond, we will then close the account for you." 
- `email`: Use their online contact us form to start the process of deletion

**Comment by tupaschoal** [comment]
Would you kindly submit a PR for this one, as you've done for the other two?

**Comment by mbtrs** [comment]
Yes definitely. I was just waiting on getting at least 1 pull request through so that I knew what to expect 😄
