### ISSUE TITLE
Add RetroAchievements

### ISSUE THREAD

**Issue by SuperSamus** [jdm-contrib/jdm#1192]
## Backstory

Actually, I don't want to delete the account and I thus I didn't try to delete it, but I noticed the "Request account deletion" button in the settings, remembered about jdm, looked at [RetroAchievements' source code](https://github.com/RetroAchievements/RAWeb/pull/519) to make sure it doesn't want any email or anything (it doesn't), and here I am.

## Data

- `name`: RetroAchievements
- `url`: https://retroachievements.org/controlpanel.php
- `difficulty`: easy
- `domains`: https://retroachievements.org

**Comment by tupaschoal** [comment]
Thanks for dropping by :)
