### ISSUE TITLE
Add Coolors

### ISSUE THREAD

**Issue by msifrt** [jdm-contrib/jdm#1196]
## Data

- `name`: Coolors
- `url`: https://coolors.co/account/delete
- `difficulty`: medium
- `notes`: Use the link provided to request account deletion. Enter your password, then you get an e-mail with a code. Enter this code in the next input field. If you created the account with a "Social Login" you need to set a password first.
- `domains`: https://coolors.co/

**Comment by tupaschoal** [comment]
Thanks for your contribution!
