### ISSUE TITLE
Add Lenovo

### ISSUE THREAD

**Issue by SuperSamus** [jdm-contrib/jdm#1204]
## Backstory

Tried the support forums because I had a problem. They weren't helpful. So I deleted the account.

The Lenovo account can actually be split into two accounts (which is why there are two "data"s): the main one (known as Lenovo ID) and the Lenovo Forums account (which depends on Lenovo ID, creating a forum account automatically creates the Lenovo ID account) (I couldn't actually find an official name for this, the closest is "Community account"). According to [this](https://forums.lenovo.com/t5/Forum-Housekeeping/Profile-error-after-changing-Lenovo-ID/m-p/5097238?page=1#5536775), if you delete Lenovo ID first, you won't be able to delete the forum account.
Also, I don't know if the labels count as "deleting": for Lenovo ID it's "Deactivate Account" (trying to login again says that the account is locked), for the forum it's "Close Account".
By the way, some information might not be 100% accurate: Lenovo's website is a mess, there is barely any documentation on this, there are multiple URLs for managing the profile with different interfaces (I have no idea what passport.lenovo.com (which many sources point to) is supposed to do, since there are basically no options there), it even changes interface and features depending on the language (for example, Italian Lenovo doesn't support login via Auth).

## Data

Lenovo ID

- `name`: Lenovo ID
- `url`: https://account.lenovo.com/us/en/account/myprofile.html
- `difficulty`: medium
- `notes`:
  - Delete the Lenovo Forums account first if you have it, otherwise you won't be able to delete it anymore.
  - Password is required: if you don't have one (because you signed in with Auth), you need to reset the password with "Forgot Password".
  - You must manually sign out after deactivation.
- `domains`: www.lenovo.com, account.lenovo.com, passport.lenovo.com 

Lenovo Forums

- `name`: Lenovo Forums
- `url`: https://forums.lenovo.com/user/myprofilepage/personal/closeaccount
- `difficulty`: easy
- `domains`: forums.lenovo.com

**Comment by tupaschoal** [comment]
Since the system is able to recognize a deactivated account, I'll put Lenovo ID as impossible.

Otherwise thanks for submitting a very detailed entry :)
