### ISSUE TITLE
Updated the playstation network entry.

### ISSUE THREAD

**Issue by therealmrmuffin** [jdm-contrib/jdm#1210]
## Backstory
One day i contacted their support and asked if it was possible to delete my account. And to my surprise it was, then i asked "how can i do this" and they said "we can do it right now if you want?" and i then said "sure'. Then after i contacted their support i get an email saying my account would be deleted and a few weeks later i got another email saying my account got deleted. Then after the second email, i tried to login again and it didn't work (verifying that my request was fulfilled).

## Data
- `name`: PlayStation Network
- `url`: https://www.playstation.com/en-us/support/account/close-account-for-psn/
- `difficulty`: Hard
- `notes`: You need to have your account email address, gamer tag, playstation serial number (or payment method, with transaction ID), and account name (not profile name) on hand to fulfill the request. This may take some time and should be done properly the first time (if possible)
- `domains`: www.playstation.com, www.sony.com, my.account.sony.com, id.sonyentertainmentnetwork.com

**Comment by tupaschoal** [comment]
Nice find, thanks!
