### ISSUE TITLE
Add 1984 Hosting.

### ISSUE THREAD

**Issue by therealmrmuffin** [jdm-contrib/jdm#1215]
## Backstory
Keeping it short: I was a 1984 hosting customer until i deiced to shutdown my website. When doing so, i also deleted my account with them. Knowing how easy their UI is the navigate, i went straight to the settings and put in the request for the account to be fully deleted. After a bit, the account was deleted as expected.    

## Data
- `name`: 1984 Hosting
- `url`: https://1984.hosting/GDPR/ (The privacy policy is the only thing that states it without contacting support) 
- `difficulty`: easy
- `notes`: Must be logged in to use the automated deletion process. 
- `email`: gdpr@1984.is
- `email_subject`: Account deletion request.
- `email_body`: Hello! Could you please delete my account? Thank you.
- `domains`: 1984.hosting, 1984hosting.com, 1984.is

**Comment by tupaschoal** [comment]
I'm confused, is it automated even if you need to send an e-mail?

**Comment by therealmrmuffin** [comment]
@tupaschoal sorry, let me clarify. Yes and no. It is indeed automated, but you can contact them if you're having problem with your account and can't do it your self (for some reason).
