### ISSUE TITLE
Intresting, must checkout.

### ISSUE THREAD

**Issue by therealmrmuffin** [jdm-contrib/jdm#1223]
Today i remember that [@tutao](https://github.com/tutao) offers free email plans to FOSS project like delete me. I wanted to mention this, because of the fact that it's a great service and that you guys could use something like their service.

Links:
https://tutanota.com/discount
https://tutanota.com/blog/posts/tutanota-for-open-source-teams/

**Comment by Nightfirecat** [comment]
Hey we appreciate the heads-up. We're not really looking for an email/calendar solution right now, free or otherwise. The project's too small to really need it. :)

**Comment by therealmrmuffin** [comment]
> Hey we appreciate the heads-up. We're not really looking for an email/calendar solution right now, free or otherwise. The project's too small to really need it. :)

Noted.
