### ISSUE TITLE
Crunchyroll deletion link may no longer work

### ISSUE THREAD

**Issue by justhereforthefood** [jdm-contrib/jdm#1306]
## Backstory

Tried to delete Crunchyroll account and the provided link gave an error: Error - Sorry, an error occurred!

## Data
`name`: Crunchyroll
`url`: https://www.crunchyroll.com/nuke

**Comment by tupaschoal** [comment]
@justhereforthefood do you have the new deletion link?

**Comment by tupaschoal** [comment]
Closing due to lack of response.

**Comment by justhereforthefood** [comment]
I've just got a confirmation from Crunchyroll support that the link no longer works and that you have to go through support at the moment to delete.

Relevant part of message below, I can forward the full email if necessary

----

Gintoki (Crunchyroll)
Aug 16, 2022, 7:42 AM PDT

Hi there!

...

Allow us to share with you that for this moment you can only delete the account through us (support tool) because for the moment the website to delete the account is not working right now for future updating. Like I told you while this happens you can delete the accounts through us the support team.

**Comment by tupaschoal** [comment]
Thanks for coming back with updated info.

**Comment by clicky6** [comment]
This link did work for me...
Is it working now?

**Comment by tupaschoal** [comment]
The nuke link, you mean @clicky6 ?

**Comment by clicky6** [comment]
> The nuke link, you mean @clicky6 ?

Yes @tupaschoal
