### ISSUE TITLE
meta always before/after name

### ISSUE THREAD

**Issue by Kefaku** [jdm-contrib/jdm#1460]
Sometimes `meta` is before `name` and sometimes after, this should be changed so the order is always the same.

e.g.:
>{
>  "name": "Amazon / Audible",
>  "meta": "popular",
>  [...]
>}

>{
>  "meta": "popular",
>  "name": "Blogger",
>  [...]
>}

**Comment by tupaschoal** [comment]
I've thought about it, but I don't want the format to be so locked in place because I think it dissuades contributions, and the project is known for receiving people with not a lot of code experience to change it afterwards

**Comment by Kefaku** [comment]
> I've thought about it, but I don't want the format to be so locked in place because I think it dissuades contributions, and the project is known for receiving people with not a lot of code experience to change it afterwards

@tupaschoal 

All other fields always have the same order, why make a difference for meta?

**Comment by tupaschoal** [comment]
I hear where you're coming from, I try to get the new additions to have the relative same order and sometimes push fixes myself. That said, I would take a PR to standardize the `meta`s to be always after `name`, but I don't want to enforce them on the CI as I don't want to make contributions more difficult, do you get what I mean?

**Comment by Kefaku** [comment]
> I hear where you're coming from, I try to get the new additions to have the relative same order and sometimes push fixes myself. That said, I would take a PR to standardize the `meta`s to be always after `name`, but I don't want to enforce them on the CI as I don't want to make contributions more difficult, do you get what I mean?

@tupaschoal 

Yeah, maybe I'll make a PR to change all existing entries to have `meta` after `name`.
