### ISSUE TITLE
2 Firefox Add-Ons?

### ISSUE THREAD

**Issue by Kefaku** [jdm-contrib/jdm#1477]
Why are there [JustDeleteMe](https://addons.mozilla.org/en-US/firefox/addon/justdeleteme/) and [Just Delete Me](https://addons.mozilla.org/en-US/firefox/addon/just-delete-me/) Add-Ons for Firefox?
Is one of them preferred/official?
Or are they now longer maintained like the Chrome extension?

Edit: I just noticed that [Just Delete Me](https://addons.mozilla.org/en-US/firefox/addon/just-delete-me/) Firefox Add-On links to the source code for the Chrome extension to contribute. That's weird?

**Comment by tupaschoal** [comment]
None of those are official. We're currently not maintaining any extensions.

The one by @alexanderepolite seemed to be an upgrade of ours that works, and we were in the process of getting it into our umbrella (https://github.com/jdm-contrib/justdelete.me-firefox-addon/issues/7), but work stalled.
