### ISSUE TITLE
can we add a section that shows what data the service's server retain after account closure?

### ISSUE THREAD

**Issue by lepras** [jdm-contrib/jdm#1480]
It will probably be difficult to know that, but we can just refer their privacy policy and/or ask on support chat.

I don't know if it would be better for jgmd or jdm but IMO jdm is a better fit.

Also can refer [tosdr](https://tosdr.org/)

For eg. Amazon saves order information for legal reasons after account closure but there could be some expiry date?

**Comment by tupaschoal** [comment]
I think this is information we rarely get and I'm ok in adding them to the notes when they are provided, so I'm closing the suggestion for now.
