### ISSUE TITLE
Proper lettering in filters

### ISSUE THREAD

**Issue by piotr-marendowski** [jdm-contrib/jdm#1486]
Hi, it seems that A - Z filter is displaying characters in lowercase, which I think should be in uppercase because you search for a service that begins with that letter. Also DIFFICULTY filter should begin with uppercase. Sorry, just being picky.
![scrot1](https://user-images.githubusercontent.com/37738748/216778240-7365dc4d-244b-4550-bdd9-d635c521ba45.png) ![scrot2](https://user-images.githubusercontent.com/37738748/216778284-5f948de8-5d8d-466c-a633-c56ceb2da49e.png)

**Comment by piotr-marendowski** [comment]
Now I realised that it would be necessary to change every translation. It would be troublesome, but I could do it. What do you think @tupaschoal? Sorry for ping.

**Comment by Nightfirecat** [comment]
I'm not really sure why this should be changed. Searching isn't case-sensitive, so I don't see why it's important that we use uppercase letters for these entries.

**Comment by piotr-marendowski** [comment]
I mean, it's only about UI, and how it looks. Just a suggestion.

**Comment by tupaschoal** [comment]
I think it provides very limited value and we'd have to have the hassle to update the translations, risking not knowing how to capitalize some of them, so I think it is fine as is for now.
