### ISSUE TITLE
Link to delete glovo account doesn't work anymore

### ISSUE THREAD

**Issue by MattiaRaffaele** [jdm-contrib/jdm#1489]
## Backstory

The link used to delete a glovo account doesn't work anymore (it gives an error 404).
I tried to fix it but I cant find any method to remove a glovo account

**To delete a glovo account you need to go to the bottom of the page and press contact us so there is not a real page where you can go it is just a popup**

## Data

{
          "name": "Glovo",
          "url": "https://glovoapp.com/en/support",
          "difficulty": "hard",
          "notes": "Enter the support website and click on 'Not related to an order' > 'Account information' > 'Delete my account and data'",
          "notes_tr": "Destek sitesini ziyaret edin ve \"Siparişle alakalı değil\" \"Hesap Bilgisi\" \"Hesabımı ve verilerimi sil\" tuşuna tıklayın",
          "notes_es": "Entrar en la web de soporte y pulsar en 'Not related to an order' > 'Account information' > 'Delete my account and data'",
          "notes_cat": "Entrar al web de suport i prémer a 'Not related to an order' > 'Account information' > 'Delete my account and data'",
          "domains": [
              "glovoapp.com"
          ]
    },

**Comment by tupaschoal** [comment]
Thanks for your contribution!
