### ISSUE TITLE
Add MMORPG.com

### ISSUE THREAD

**Issue by sealldeveloper** [jdm-contrib/jdm#1492]
## Backstory

Went to the URL, deleted it, very easy.

## Data

- `name`: MMORPG.com
- `url`: https://www.mmorpg.com/notice/delete-account
- `difficulty`: easy
- `notes`: Visit the URL, confirm deletion of the account.
- `domains`: mmorpg.com

**Comment by tupaschoal** [comment]
Thanks for all the entry suggestions!
