### ISSUE TITLE
kraken.com gets mistaken for gitkraken.com

### ISSUE THREAD

**Issue by array-in-a-matrix** [jdm-contrib/jdm#1524]
This seems to be a problem on only [www.kraken.com](https://www.kraken.com) as [support.kraken.com](https://support.kraken.com) is detected correctly.

![image](https://user-images.githubusercontent.com/78233840/222864161-6b8fa889-cb23-4175-a1dc-e5a406de2e71.png)

**Comment by tupaschoal** [comment]
Please open an issue on one of the extension repos.
