### ISSUE TITLE
Hover color in about section is not accessible

### ISSUE THREAD

**Issue by WebSnke** [jdm-contrib/jdm#1556]
The hover color text for the links in the about section is red which does not provide a good contrast, especially for people with bad vision.

This is how it looks:
![image](https://user-images.githubusercontent.com/94064167/227302170-99d51856-5ba5-48d7-a57e-f45b4c465329.png)

The problem:
![image](https://user-images.githubusercontent.com/94064167/227302365-f353c6ae-cdef-4c31-9e08-bd1f4d84d6c8.png)

**Comment by WebSnke** [comment]
Could someone add appropriate labels, please? Thanks.

**Comment by MattiaRaffaele** [comment]
I think that when you put the cursor on the label you have already read the text so I think that this won't make any changes to people with bad vision

**Comment by MattiaRaffaele** [comment]
> I think that when you put the cursor on the label you have already read the text so I think that this won't make any changes to people with bad vision

PS I also think that the green and red aren't good so for me someone should make the hover text color white or black
