### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by whinee** [jdm-contrib/jdm#1562]
## Backstory

Me just noticed that I can't delete my pypi account if I'm the sole owner of a project/s, and i have to transfer ownserhsip of em, or just delete em. I think changing the difficulty to medium is justifiable, but I do not really know if deviating from a simple single click of a button to delete ur account into a multi-step process for others can warrant such change.

In any case, I have not deleted my PyPi account, so I do not know if me doing those things will finally allow me to delete my PyPi account, but it seems to be that way. Fully testing might be required, but deleting my own account would inconvenience me, so someone might be up to do that.

## Data

- `difficulty`: medium
- `notes`: Go to "Delete account > Delete your PyPI account". Project/s that you are the sole of owner of will be needed to have their ownership transferred to another user or to be deleted before being able to proceed.

**Comment by tupaschoal** [comment]
Thanks for letting us know!

**Comment by whinee** [comment]
No problem!
