### ISSUE TITLE
Update SurveyTime

### ISSUE THREAD

**Issue by basketshoe** [jdm-contrib/jdm#1620]
## Backstory

As written on https://surveytime.io/privacy-policy:

> You may request that we delete the Personal Information that we collected about you. By asking us to delete your Personal Information we will have to close your account and you will no longer be able to use the Surveytime site and Features or our Services. Please note that your Surveytime account cannot be reinstated once it has been deleted.
> 
> If you want to delete your Surveytime account, please submit your requests by: (1) Emailing us at [Surveytime Contact Email;](mailto:tommy@surveytime.io) (2) Tapping the "Delete your account" button in the Mobile App Settings screen and completing the process. We will process your request for removal within 10 business days, although we attempt to process it within 24 hours.
> 

## Data

- `name`: SurveyTime
- `url`: surveytime.io/privacy-policy
- `difficulty`: medium
- `email`: tommy@surveytime.io
- `email_subject`: Account deletion request
- `email_body`: Please delete the account linked to this email
- `domains`: surveytime.io

**Comment by tupaschoal** [comment]
Thanks for your contribution!

**Comment by basketshoe** [comment]
The procedure should be :

> You have to mail them requesting deletion **or** tap the "Delete your account" button in the Mobile App Settings screen.

not

> You have to mail them requesting deletion **and then** tap the "Delete your account" button in the Mobile App Settings screen.

**Comment by basketshoe** [comment]
The second one

**Comment by tupaschoal** [comment]
Fixed it, thanks!
