### ISSUE TITLE
Update About the StackExchnage Network

### ISSUE THREAD

**Issue by zer0-x** [jdm-contrib/jdm#1665]
## Backstory

When I tried to delete my accounts in the Stack Exchange Network, it was easy to delete my account from the associated sites with the currently provided method, like: `stackoverflow.com` and `tex.stackexchange.com`. Later I noticed that I still have an account and profile in https://stackexchange.com/ (which is the main website of the network, it lists all your account in the network in one single profile). My profile was empty with no associated posts or account. I tried to find a delete button but I couldn't.

Later I contacted support and they said that I need to submit an `Erase my account` request from this page: https://stackoverflow.com/legal/gdpr/request

Later after two days, they sent a message to my email to inform me that my profile was fully deleted and my data was removed or anonymized in the network.

## Data

- `name`: Stack Exchange Accounts
- `url`: https://stackoverflow.com/help/deleting-account and https://stackoverflow.com/legal/gdpr/request
- `difficulty`: hard

**Comment by Kefaku** [comment]
Wouldn't it be 'limited', instead of 'hard', if it's a GDPR request?

**Comment by zer0-x** [comment]
Well, I'm not in in the European Union and it worked for me.

In my country we have a law almost similar to GDPR but it has not been enforced yet. Anyway, I don't think they looked at.
