### ISSUE TITLE
Add TV Tropes

### ISSUE THREAD

**Issue by SuperSamus** [jdm-contrib/jdm#1691]
## Backstory

I actually didn't test any of this.

## Data

- `name`: TV Tropes
- `url`: https://tvtropes.org/pmwiki/profile.php
- `difficulty`: easy
- `domains`: https://tvtropes.org/

According to the [FAQ](https://tvtropes.org/pmwiki/pmwiki.php/Main/FAQ):
> In your [profile](https://tvtropes.org/pmwiki/profile.php), there is a 'Delete Account' link. Clicking this will permanently delete all personal information from your user profile and deactivate your account. Your username cannot be used again by you or anyone else.

![image](https://github.com/jdm-contrib/jdm/assets/40663462/2cc5009d-ee76-45a9-a8ed-7fbb056d1a27)

**Comment by MattiaRaffaele** [comment]
I can do that
