### ISSUE TITLE
Add videos with notes

### ISSUE THREAD

**Issue by MattiaRaffaele** [jdm-contrib/jdm#1698]
# Introduction
Hi! I recently had an idea for your service, here I will explain my idea and if I (surely) didn't explain well and you have some doubts you can ask me here.

# Main idea
The idea is to add videos within the notes so that when people try to delete their account they can read the `notes` and also see a YouTube video.

We could implement that with a _watch video_ like is currently possible to do with emails (when you need to send an email for an account deletion) or more complicated add the thumbnail of the video with a play button on it.

![idea num 1](https://github.com/jdm-contrib/jdm/assets/88104208/2cbb34bd-ab0c-4669-8c87-e76c1ad37c3f)

**Comment by Nightfirecat** [comment]
How frequently would this be needed? It's already possible to add links to note text if there's some reason further information needs to be linked. For most entries, I don't see how a video would meaningfully improve the existing link and notes.

**Comment by MattiaRaffaele** [comment]
> How frequently would this be needed? It's already possible to add links to note text if there's some reason further information needs to be linked. For most entries, I don't see how a video would meaningfully improve the existing link and notes.

I thought it should be helpful when the site doesnt let you delete your account until you delete (for example teams organisations etc...) and when the account deletion is more complicated that it needs more steps

**Comment by tupaschoal** [comment]
I can see how a video would help with the most convoluted processes, but I'm a bit skeptic at how many people would be willing to record videos, as it takes some time. Can you name a service where you think a video would come in handy?

**Comment by MattiaRaffaele** [comment]
> I can see how a video would help with the most convoluted processes, but I'm a bit skeptic at how many people would be willing to record videos, as it takes some time. Can you name a service where you think a video would come in handy?

The creator of the pull request doesn't necessarily need to record a video he can just find a link on the web and paste it

**Comment by tupaschoal** [comment]
Sure. So going back to my other point, can you name a service where you think a video would come in handy?

**Comment by MattiaRaffaele** [comment]
I saw tutorial videos videos for [Roblox](https://www.youtube.com/watch?v=8u9yKKAlZts&ab_channel=GuideRealm) and [Facebook](https://www.youtube.com/watch?v=nED3BancUyc&ab_channel=TrevorNace)
