### ISSUE TITLE
Update League of Legends

### ISSUE THREAD

**Issue by Glowiz** [jdm-contrib/jdm#1711]
## Backstory

Was trying to delete my LOL account and found an easier way than to fill a ticket by hand.

## Data

- `name`: League of Legends
- `url`: https://support-leagueoflegends.riotgames.com/hc/en-us/articles/360050328454
- `difficulty`: Easy
- `notes`: Go to the page and confirm your deletion.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by Kefaku** [comment]
Is that specific to LoL or do all Riot Games use the same account and which can be deleted that way?

**Comment by Glowiz** [comment]
Good point there, I was looking to delete my LOL account made years ago that i never used on any other game so I didn't pay attention, but it might as well be the whole Riot account, I'll go check that later.

**Comment by Kefaku** [comment]
> Good point there, I was looking to delete my LOL account made years ago that i never used on any other game so I didn't pay attention, but it might as well be the whole Riot account, I'll go check that later.

I just checked myself. Every Riot Game seems to have a seperate support article, but a similar procedure; I made a PR
