### ISSUE TITLE
Change Shopify's Difficulty

### ISSUE THREAD

**Issue by EmmaScripted** [jdm-contrib/jdm#1718]
## Backstory

So I was trying to delete my shopify account as I found a better and cheaper alternative to it and I thought it would be easy as said in the website, however, the steps that it shows only show you how to close a store, not how to close your account, your account is still there after you close your store meaning they still have your data, I did more research and found out it's impossible to delete your account but if you contact support they can deactivate it for you.

## Data

- `name`: Shopify
- `url`: https://help.shopify.com/en/manual/your-account/pause-deactivate-store#close-your-store 
- `difficulty`: Hard
- `notes`: Go to the support page until you reach the option "Chat with us!" and create a ticket to talk with a support agent and tell them to delete your account/data
- `domains`: https://www.shopify.com

**Comment by EmmaScripted** [comment]
Yeah so they don't delete it, it's just not active anymore meaning that it doesn't receive charges and stuff, heres a screenshot of the chat 
![image](https://github.com/jdm-contrib/jdm/assets/61598574/d27ecf23-c258-46db-b4dc-d17f6a6fecca)

**Comment by tupaschoal** [comment]
Yeah, if they never delete it, definitely should be moved to impossible. Thanks for letting us know!
