### ISSUE TITLE
Add Site - MasalaDesi

### ISSUE THREAD

**Issue by Manup5u** [jdm-contrib/jdm#1731]
## Backstory

I created an account in a site named 'MasalaDesi' by using my Gmail id. Earlier their site's url were: https://masaladesi.club/.
Recently they changed their URL to: https://jollyvids.com/forum-videos. They informed that they changed their domain because of their old domain was blocked by several Internet Service Providers (ISPs). Still their site's name is - MasalaDesi. Now when i going to delete my account from this site, there is no account deletion option. When i asked about it, they replied me that the account can't be deleted. But in your chrome extention, it shows that the difficulty level to delete that site's account is Easy. I request you to help me to add that site in your service's directory and also add that in your chrome extention also and please help me to delete my account from the site - https://jollyvids.com/forum-videos. I hope may you help me. 
     ->

## Data

- `name`:  MasalaDesi
- `url`:  https://jollyvids.com/forum-videos
- `difficulty`: Easy

- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: https://jollyvids.com/forum-videos.

**Comment by Manup5u** [comment]
Can you help me to delete my account from the site : https://jollyvids.com/forum-videos.?

**Comment by tupaschoal** [comment]
Hi @Manup5u,

Unfortunately we don't actively seek steps for deletion for the users, we rely on the users themselves contributing back with what they found, so we cannot help you delete your account at jollyvids at this time.
