### ISSUE TITLE
Add Site

### ISSUE THREAD

**Issue by Manup5u** [jdm-contrib/jdm#1733]
## Data

- `name`: MasalaDesi
- `url`: https://jollyvids.com/
- `url_CODE`: 
- `difficulty`: Easy
- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: https://jollyvids.com/forum-videos

**Comment by tupaschoal** [comment]
Have you figured out how to delete the account @Manup5u ? If so, can you let us know the steps please?
