### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Manus123s** [jdm-contrib/jdm#1750]
.

**Comment by Manus123s** [comment]
Ok. If i didn't login that site for a long time, is there any possibilities to delete my account by admins themselves? Because they already banned my account permanently. What's your opinion and assumption regarding it?

**Comment by Kefaku** [comment]
Since they didn't delete your account even after you asked them (and only banned it), I think it is unlikely that they will delete it in the future.

**Comment by Manus123s** [comment]
Their previous domain (Masaladesi.club) is banned in my country (India) by
government in last year. I was created my account in that domain. When the
government in my country banned that site in last year, now they changed
their domain to - jollyvids.com.

**Comment by Manus123s** [comment]
Sir, their previous domain (Masaladesi.club) is banned in my country
(India) by government in last year. I was created my account in that
domain. When the government in my country banned that site in last year,
now they changed their domain to - jollyvids.com.
