### ISSUE TITLE
Update Pocket Casts

### ISSUE THREAD

**Issue by mylespm** [jdm-contrib/jdm#1759]
## Backstory

You can delete your account directly from the app now. No need to email customer support.
I asked their support chat bot and it gave the instructions below.

## Data

- `name`: Pocket Casts
- `url`:
- `difficulty`: Easy
- `notes`:

For iOS:

    Open the Pocket Casts app.
    Click on the "Profile" tab.
    Click on your account email address.
    Scroll down and click on "Delete Account" at the bottom of the screen.

For Android:

    Open the Pocket Casts app.
    Click on the "Profile" tab.
    Click on "Account."
    Scroll down and click on "Delete account" at the bottom of the screen.

For Web:

    Log in to the Pocket Casts web player using your account credentials.
    Click on the profile icon in the top right-hand corner of the screen.
    Click on your email address to access the Profile screen.
    Scroll down and click on the "Delete Account" link.
    A confirmation pop-up will appear asking if you're sure you want to delete your account. Click "Delete" to confirm.

**Comment by tupaschoal** [comment]
Thanks for your contribution!
