### ISSUE TITLE
Add IBMid

### ISSUE THREAD

**Issue by Thanos1716** [jdm-contrib/jdm#1788]
## Backstory

Struggled to find this URL, but after finding it and reading the `How do I delete my IBMid` section, I contacted the relevant help desk using a template from [yourdigitalrights.org](https://yourdigitalrights.org/), 17 days later I get a deletion confirmation
Hope this saves someone some time

## Data

- `name`: IBMid
- `url`: https://www.ibm.com/ibmid/myibm/help/us/helpdesk.html
- `difficulty`: hard
- `notes`: Contact your relevant help desk, and an email should be sent back with confirmation of deletion
- `email`: ibmidsupport@ibm.com or ibmidsupportuk@ibm.com (depending on your country)
- `email_body`: I generated a relevant body using [yourdigitalrights.org](https://yourdigitalrights.org/)
- `domains`: https://www.ibm.com

**Comment by Kefaku** [comment]
Shouldn't this be "hard", since you need to contact customer support?

**Comment by Kefaku** [comment]
> Potentially, I did not consider the process too difficult once I knew where to go, but I can change it if you think it reflects the other ratings better

The website say hard means: "Cannot be fully deleted without contacting customer services"

**Comment by tupaschoal** [comment]
Thanks for your contribution!
