### ISSUE TITLE
Update Aeria Games (now Glyph.net and Gamigo.com)

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#1793]
## Backstory

Website redirects to a new service.

## Data

- `name`: Glyph
- `url`: https://support.gamigo.com/hc/en-us/articles/204884188-How-do-I-delete-my-Glyph-account-
- `difficulty`: easy
- `notes`: requires a support ticket
- `domains`: gamigo.com, glyph.net

**Comment by Kefaku** [comment]
An entry for Glyph / Gamigo already exists, seems like we'd simply need to delete the old Aerie Games entry, right?

**Comment by tupaschoal** [comment]
Closing for lack of response
