### ISSUE TITLE
Add Withings

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#1794]
## Backstory

Can delete your account easily after logging in with one click

## Data

- `name`: Withings
- `url`: https://account.withings.com/account/account_delete
- `difficulty`: easy
- `notes`: Can delete your account after logging in, in one click from the user settings page. You can also choose to have your data sent to you first. The deletion process takes 7 days.
- `domains`: https://withings.com

**Comment by tupaschoal** [comment]
Thanks for the suggestion!
