### ISSUE TITLE
Add Bikemap

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#1795]
## Backstory

Delete account in 1 click from website

## Data

- `name`: Bikemap
- `url`: [](https://help.bikemap.net/hc/en-us/articles/360017408820-Deleting-my-Bikemap-account#:~:text=Press%20on%20the%20profile%20tab,and%20click%20%22Delete%20Account%22.)
- `difficulty`: Easy
- `notes`: Login, click settings, scroll down to delete account
- `domains`: https://bikemap.net

**Comment by tupaschoal** [comment]
Thanks for your suggestion!
