### ISSUE TITLE
Add FitnessSyncer

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#1796]
## Backstory

Login and delete account from profile page

## Data

- `name`: FitnessSyncer
- `url`: https://www.fitnesssyncer.com/account#Profile
- `difficulty`: Easy
- `notes`: Login, click profile link, scroll down to delete and confirm
- `domains`: https://www.fitnesssyncer.com/

**Comment by tupaschoal** [comment]
Thanks for the suggestion :)
