### ISSUE TITLE
Add Joom

### ISSUE THREAD

**Issue by alexaka1** [jdm-contrib/jdm#1798]
## Data

- `name`: Joom
- `url`: `https://www.joom.com/en/privacy`
- `difficulty`: `easy`
- `notes`: Login to your account, scroll down to the bottom of the privacy policy and click `delete account`. Confirm the deletion dialog. `OPTIONAL` Enter an email address to be notified of when deletion completes.
- `domains`: `www.joom.com`

**Comment by tupaschoal** [comment]
Thanks for the suggestion!
