### ISSUE TITLE
Add The Epoch Times

### ISSUE THREAD

**Issue by dax0lotl** [jdm-contrib/jdm#1801]
## Backstory

Epoch Times is beyond problematic. I looked for a delete account button after I thought i unsubscribed but they kept sending me emails. Eventually I contacted customer support, and I was NOT nice about it.

## Data

- `name`: The Epoch Times
- `url`: https://help.theepochtimes.com/hc/en-us/requests/new 
- `url_CODE`: 
- `difficulty`: Hard 
- `notes`: Send a request to customer support demanding for the deletion of your account. 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: https://www.theepochtimes.com/

**Comment by tupaschoal** [comment]
Thanks for the suggestion!
