### ISSUE TITLE
Add Genymotion Desktop

### ISSUE THREAD

**Issue by Thanos1716** [jdm-contrib/jdm#1814]
## Backstory

Found an account verification email from them (I don't remember signing up), so I tried resetting password and logging in.
Very easy.
It should be noted that a Genymotion Desktop account is different from Genymotion Cloud (SaaS) account.

## Data

- `name`: Genymotion Desktop
- `url`: https://www-v1.genymotion.com/account/#account-info
- `difficulty`: Easy
- `notes`: Log in, and on the "Account Info" tab, scroll to the bottom and click "Delete account". There should then be a confirmation box, where you can delete your account.
- `domains`: `https://www-v1.genymotion.com/`, `https://www.genymotion.com/` (second one is a homepage for both the desktop account and the cloud account, so may cause an issue in future?)

**Comment by Kefaku** [comment]
I propose using the following values for Genymotion Cloud. I'll make a PR implementing both Genymotion Desktop and Cloud later today.

## Data

- `name`: Genymotion Cloud (SaaS)
- `url`: https://support.genymotion.com/hc/en-us/requests/new?ticket_form_id=360000289657
- `difficulty`: hard
- `notes`: First, log in to your account and go to the [Administration Panel](https://docs.genymotion.com/saas/latest/05_Administration_interface.html#administration-interface), cancel your plan and remove all credit card. \nAfter doing that, you can [submit a support ticket requesting the account deletion](https://support.genymotion.com/hc/en-us/requests/new?ticket_form_id=360000289657).
- `domains`: `https://geny.io/`, `https://cloud.geny.io/`
