### ISSUE TITLE
Groupon locale

### ISSUE THREAD

**Issue by threadcraft** [jdm-contrib/jdm#1835]
https://github.com/jdm-contrib/jdm/blob/73a8e25a72691947b6eb4282b680c86acabda630/_data/sites.json#L7868

This link doesn't work for US based accounts, https://privacy.groupon.com works

**Comment by Kefaku** [comment]
Does https://privacy.groupon.com/ also work for UK based accouts, or is that specific to the US?

**Comment by sean-mckee** [comment]
I'm not sure, I wonder if "groupon.co.uk" and "groupon.com" should be treated as separate sites, they seems to have different back-ends.

**Comment by sean-mckee** [comment]
On privacy.groupon.com > click "data request" button > select "delete all my data" 

![image](https://github.com/jdm-contrib/jdm/assets/8726742/897cb233-b32a-48d9-b4ed-e5fd1372ba51)

![image](https://github.com/jdm-contrib/jdm/assets/8726742/b79e81b7-c1d4-45ee-b987-b934cec96fad)

**Comment by tupaschoal** [comment]
Thanks for your contribution!
