### ISSUE TITLE
Rakuten

### ISSUE THREAD

**Issue by threadcraft** [jdm-contrib/jdm#1839]
https://github.com/jdm-contrib/jdm/blob/5a8dea206e7d8bba75da93727cc02156d660b8d6/_data/sites.json#L14687

I was able to delete my account easily using this,
https://www.rakuten.com/privacy-preferences.htm

**Comment by Kefaku** [comment]
As the website states:
![info](https://github.com/jdm-contrib/jdm/assets/114934849/37ce7d67-ab09-4d53-9338-a0c463f138cb)

The method you mentioned is only available in regions with appropriate privacy laws in place. For example:

![cal](https://github.com/jdm-contrib/jdm/assets/114934849/84ec6402-3b66-4dab-a51b-5c3655498eb8)

vs:

![non](https://github.com/jdm-contrib/jdm/assets/114934849/bfdf5868-6fcf-4cd2-9c12-c94d628ea12d)

Although I'm not sure whether the method currently mentioned on https://justdeleteme.xyz is truly `hard` or also `limited`.

**Comment by Kefaku** [comment]
I just found out their [ToS](https://www.rakuten.com/help/article/terms-conditions-360002101608) say

> 2.1 Our Programs are not available to and should not be accessed or used by residents outside of the 50 United States or Washington D.C.

Wouldn't that make it always limited? Please help here @tupaschoal.

**Comment by tupaschoal** [comment]
Technically it would, but we make it `limited` only when they actually enforce it.

What did you mean when you said "you could delete it easily" @sean-mckee? Is it just accessing the page and hitting a delete button?

**Comment by sean-mckee** [comment]
Yes it was just as easy as hitting a delete button, but I am in California, so I may be getting region specific options.

**Comment by tupaschoal** [comment]
Thanks!
