### ISSUE TITLE
Add MinID

### ISSUE THREAD

**Issue by pistasjis** [jdm-contrib/jdm#1846]
## Backstory

I haven't deleted my account, but I was looking into it out of curiosity. This is Norway's state-owned ID solution made by the Digitalisation Agency.

## Data

- `name`: MinID
- `url`: [https://eid.difi.no/en/minid/blocking-minid](https://eid.difi.no/en/minid/blocking-minid)
- `url_CODE`: don't know how to use this. but you can probably replace en with nb / nn 
- `difficulty`: hard
- `notes`: You need to "block" your MinID first by sending a form. If you'd also like to be removed from the contact registry, you'll need to submit a form to delete your information from the contact registry.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: minid.no

**Comment by tupaschoal** [comment]
Thanks for your contribution!
