### ISSUE TITLE
Duplicate key `notes_it` for service `Algor Education`

### ISSUE THREAD

**Issue by Kefaku** [jdm-contrib/jdm#1847]
There seem to be two different entries for the `notes_it` key for the same service (`Algor Education`).

https://github.com/jdm-contrib/jdm/blob/22c82a0aaafe1912f59ffc81a7cfa9b83b99f8f9/_data/sites.json#L878

https://github.com/jdm-contrib/jdm/blob/22c82a0aaafe1912f59ffc81a7cfa9b83b99f8f9/_data/sites.json#L883

**Comment by Nightfirecat** [comment]
Hmm, we should add some detection for that.
