### ISSUE TITLE
Novelai.net

### ISSUE THREAD

**Issue by dax0lotl** [jdm-contrib/jdm#1862]
## Backstory

Novelai.net is a world-building website that uses artificial intelligence to enhance creative potential. The ui is a bit cluttered, and certain buttons don't have clear purposes until you click on them.

## Data

- `name`: Novel ai

- `url`: https://novelai.net/stories

- `url_CODE`: 

- `difficulty`: Medium

- `notes`: Log into your account, and press your account icon in the top left corner of the screen. Go to account settings, and press the deletion request button. enter your email, click the "account deletion link" in your inbox, and press the confirmation button after being redirected. Your data should be deleted after 24 hours.

- `domains`: https://novelai.net/

**Comment by tupaschoal** [comment]
Thanks!
