### ISSUE TITLE
Add Fanatical

### ISSUE THREAD

**Issue by Celesian** [jdm-contrib/jdm#1872]
## Backstory
I went into the settings to look for the account deletion and found it 

## Data

- `name`: Fanatical
- `url`: https://support.fanatical.com/hc/en-us/articles/202230392-How-do-I-delete-or-close-my-Fanatical-account-
- `difficulty`: Easy
- `domains`: www.fanatical.com

**Comment by tupaschoal** [comment]
Tackled by #1873
