### ISSUE TITLE
Add Exophase

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#1891]
## Backstory

They delete your account in 72 hours and it also includes the forum account attached. You must keep your connected services attached during this time so they can be fully removed by an admin. Your connected services (Playstation, Xbox etc) also cannot be added to a future account without contacting a staff member.

## Data

- `name`: Exophase
- `url`: https://www.exophase.com/account/removal/
- `difficulty`: Easy
- `domains`: https://www.exophase.com

**Comment by Kefaku** [comment]
@825i said:
> Your connected services (Playstation, Xbox etc) also cannot be added to a future account without contacting a staff member.

If that is the case, they must retain data on your connected services, else they wouldn't know they had been connected to an account previously. That would be contradictory to their statement in [their FAQ](https://www.exophase.com/faq/):
> all data related to your account will be removed from our servers

**Comment by tupaschoal** [comment]
Closing for lack of response, if you can answer @Kefaku 's query, please do and reopen!

**Comment by tupaschoal** [comment]
Will add as hard, since it requires you to keep some stuff attached until deletion and etc. #2249
