### ISSUE TITLE
Make URL requirement optional

### ISSUE THREAD

**Issue by MyFedora** [jdm-contrib/jdm#1895]
> The url of the account-deletion page. If no such page exists, the url should be a contact or help page explaining the process of account deletion.

Unfortunately, a few services don't want to delete our data.

- Services that don't have an account deletion page.
- Services that auto close account deletion support tickets.
- Services that don't have an account deletion help page, or have one with false information.
- Services that have multiple distinct forms to request account deletion depending on the jurisdiction.

Services that match all of the preceding criteria can't be on JDM. For example: Crunchyroll.

I only need to contact Crunchyroll support, according to the JDM entry. Crunchyroll's [account deletion help page](https://help.crunchyroll.com/hc/en-us/articles/18504034087572-How-can-I-delete-my-account-) confirms this, but their reply tells a different story:

> Hi there,
>
> Thanks for reaching out to us. The security of your data is our top priority! Please be aware Crunchyroll customer support no longer directly handles customer data requests for GDPR, CCPA, and LGPD. Below, you'll find a list of links for all of your Crunchyroll data fulfillment needs! Just be sure to select "Crunchyroll/Crunchyroll Games" as your service.
>
> Please note that for CCPA requests "Do not share" (DNS) requests are in a separate form, provided below.
>
> ##### [CCPA Request Form](https://privacyportal.onetrust.com/webform/d19e506f-1a64-463d-94e4-914dd635817d/fc46fc0c-407c-4735-9a43-14dfa283d17c)
>
> ##### [CCPA DNS Request Form](https://privacyportal.onetrust.com/webform/d19e506f-1a64-463d-94e4-914dd635817d/b9eb997c-9ede-451b-8fd4-29891782a928)
>
> ##### [All Other Requests](https://sites.sonypictures.com/corp/privacypolicies/b2c/contact-us.html)
>
> Let us know if you have any questions!
>
> Best,

Okay, great.

- Crunchyroll doesn't have an account-deletion page.
- Crunchyroll auto closes account deletion support tickets.
- Crunchyroll has an account deletion help page with false information.
- Crunchyroll has multiple distinct forms to request account deletion depending on the jurisdiction.

What am I supposed to use as url here? No account deletion page, no contact page, false help page. Multiple forms to fill out depending on the jurisdiction. It feels like the url should either be optional or another data structure.

**Comment by SteffenGivard** [comment]
Just to make sure I understand, did you get the cited reply after filling the request form on Crunchyroll? <details><summary>(The form I'm referencing)</summary>
<img src="https://github.com/jdm-contrib/jdm/assets/2188806/585a4936-ede6-4cd9-a207-db597f8a1fd2">
</details>

**Comment by MyFedora** [comment]
> Just to make sure I understand, did you get the cited reply after filling the request form on Crunchyroll?

Yes.

**Comment by SteffenGivard** [comment]
I see. Makes sense to have the URL be optional in this case.
For the time being, what about having the URL be to your post in this issue thread, and then add the links you quoted to the notes?

**Comment by SteffenGivard** [comment]
> Do you want to get credit for the suggestion to point the URL to this thread in the form of the `Suggested-by:` tag?
Only because I've never seen the `Suggested-by:` tag before 😀

**Comment by tupaschoal** [comment]
I like having a URL, I don't want to make it optional for the time being, but I like your suggestion to use a discussion like here.
