### ISSUE TITLE
Update Binance

### ISSUE THREAD

**Issue by basketshoe** [jdm-contrib/jdm#1928]
## Backstory

Had to delete account and the link on jdm did not work

## Data

- `name`: Binance
- `url`: https://www.binance.com/en/my/security
- `difficulty`: easy
- `notes`: Go to the website linked, scroll down and click on "delete account", then follow the steps
- `domains`: https://www.binance.com/

**Comment by tupaschoal** [comment]
Thanks for your contribution!
