### ISSUE TITLE
Add VidIQ

### ISSUE THREAD

**Issue by PsychotherapistSam** [jdm-contrib/jdm#1953]
## Backstory

I looked through the account settings page and couldn't find anything about account deletion. After a quick Google search I sumbled across a Video stating that the Account can only be deleted via a support request.
After sending a message to the Chat Bot on the Profile page, and then confirming the account deletion to that bot, I got this response:

The team will get back to you on this. vidIQ typically replies in a few hours.

Although a team member responded within 5 Minutes or so.

## Data

- `name`: VidIQ
- `url`: https://app.vidiq.com/account/settings/my-account
- `notes`: You have to cancel your Subscription before writing the Support (Bot)
- `difficulty`: hard
- `domains`: app.vidiq.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
