### ISSUE TITLE
check_files_formatting does not seem to be erroring out

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#1966]
#1965 had a bunch of trailing spaces and tabs, nevertheless the `check_files_formatting.sh` passed, but when checking the log, the following could be seen:

```
File: /home/runner/work/jdm/jdm/_data/sites.json
Line: 1494 Unexpected trailing spaces found. [warning]
Line: 1496 Unexpected tabs found. [warning]
Line: 1497 Unexpected tabs found. [warning]
Line: 1498 Unexpected tabs found. [warning]
Line: 1499 Unexpected tabs found. [warning]
Line: 1500 Unexpected tabs found. [warning]
Line: 1501 Unexpected tabs found. [warning]
Line: 1502 Unexpected tabs found. [warning]
Line: 1503 Unexpected tabs found. [warning]
Line: 1504 Unexpected trailing spaces found. [warning]
```

This suggests that the errors at some point became warnings. I'm attaching the log
[logs_3196.zip](https://github.com/jdm-contrib/jdm/files/14250998/logs_3196.zip)

**Comment by Nightfirecat** [comment]
I'm not sure which PR you're trying to link to; we haven't reached 2557 issues/PRs yet :sweat_smile: 

[It looks like @htmlacademy/editorconfig-cli has changed a lot in the past year](https://www.npmjs.com/package/@htmlacademy/editorconfig-cli?activeTab=versions), so it's possible it no longer behaves the way we need it to. I do get the expected behavior (that is, non-0 exit code) on v1.0.0, so I will look at pinning the version so we can have it working again.

**Comment by tupaschoal** [comment]
One thing that I noticed is that previously the editor config errored out, but somehow GH Actions failed to report the proper line, like this example on a recent PR:
```
Run script/check_files_formatting.sh
Using '.editorconfig' from: "/home/runner/work/jdm/jdm/.editorconfig"

File: /home/runner/work/jdm/jdm/_data/sites.json
Warning: 9 Unexpected trailing spaces found. [warning]
Error: Process completed with exit code 1.
```

I don't know why that happens, if it's something that was fixed with later versions (despite warnings not becoming an error), because running the script as is today reports the lines correctly for me (although it also reports several stuff on `_pages` path that CI doesn't show.

I was wondering whether we could move to the latest version and use pipes to redirect the stdout/stderr to a file and then count that grep for warnings is 0

**Comment by tupaschoal** [comment]
Something else is amiss, according to the `editorconfig-cli` code, it should bail out on warnings and also print them as red, but as I saw on the logs and local runs, it prints it in yellow and exits with 0, so something is broken there:

https://github.com/htmlacademy/editorconfig-cli/blob/6b11a6c1fbcf50c84e8ecd80043673c5e0b1af38/index.js#L85-L92

**Comment by tupaschoal** [comment]
I've opened a PR (as seen linked above) with a candidate fix
