### ISSUE TITLE
Add wikiHow

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#1984]
## Backstory

![image](https://github.com/jdm-contrib/jdm/assets/48226312/ca1f13c3-a2d6-4dd1-84da-3be859e1d748)
It's clearly written there to mail for deletion

## Data

- `name`: wikiHow
- `url`: https://www.wikihow.com/Special:Preferences#mw-prefsection-personal
- `url_CODE`: 
- `difficulty`: hard
- `notes`: 
- `email`: privacy@wikihow.com
- `email_subject`: 
- `email_body`: 
- `domains`: wikihow.com

**Comment by tupaschoal** [comment]
If it requires emailing, then it is hard

**Comment by shuvashish76** [comment]
Thanks just double checked CONTRIBUTING.md.

**Comment by tupaschoal** [comment]
Thanks for your contribution!
