### ISSUE TITLE
Update Clockify

### ISSUE THREAD

**Issue by Vhivi** [jdm-contrib/jdm#1986]
## Backstory

The link no longer works.

The proposed link is [https://clockify.me/user/settings/delete](https://clockify.me/user/settings/delete), the current link is [https://app.clockify.me/user/settings/delete](https://app.clockify.me/user/settings/delete).

## Data

- `name`: Clockify
- `url`: [https://app.clockify.me/user/settings/delete](https://app.clockify.me/user/settings/delete)
- `difficulty`: easy
- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: clockify.me

**Comment by tupaschoal** [comment]
Thanks for your contribution!
