### ISSUE TITLE
Add wallabag

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#1988]
## Backstory

https://github.com/wallabag/wallabag
wallabag is a self hostable application for saving web pages.
They offer 14-day free trial.

## Data

- `name`: wallabag
- `url`: https://app.wallabag.it/subscription/
- `url_CODE`: 
- `difficulty`: easy
- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: wallabag.org, wallabag.it, app.wallabag.it

**Comment by tupaschoal** [comment]
Thanks for your contribution!
