### ISSUE TITLE
Update Transifex

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#1989]
## Data

- `name`: Transifex
- `url`: https://app.transifex.com/user/settings/
- `difficulty`: easy
- `notes`: Click on the link, scroll to the bottom and click Delete my account; confirm it in the popup view by entering your password for deletion.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: transifex.com, app.transifex.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
