### ISSUE TITLE
Sdc.com

### ISSUE THREAD

**Issue by tiagodamian** [jdm-contrib/jdm#2001]
## Backstory

Went to website e found delete acount under acc settings

## Data

- `name`: Sdc.com
- `url`: www.sdc.com/react/#/settings2
- `url_CODE`: 
- `difficulty`: easy
- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by tupaschoal** [comment]
Thanks for your contribution!
