### ISSUE TITLE
Add Z-Library

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#2011]
## Backstory

Z-Library is considered as one of the largest e-book shadow library.
There are many fake sites appearing as z-lib but what I've mentioned are the official ones. (Source: [Wikipedia](https://en.wikipedia.org/wiki/Z-Library), [Mastodon](https://mastodon.social/@Z_Lib_official))

The account deletion page goes like this `https://domain/profileEdit#tabRemove`. Due to multiple seizures & ever changing domains I think better to add them as notes.

## Data

- `name`: Z-Library
- `url`: 
- `url_CODE`: 
- `difficulty`: medium
- `notes`: Click on top-right-cornor menu > Edit Profile > Remove Profile > Remove my account. Enter Captcha to remove account permanently. Note that you'll unable to create a new account associated with this emailID.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`: singlelogin.re, z-library.se, loginzlib2vrak5zzpcocc3ouizykn6k5qecgj2tzlnab5wcbqhembyd.onion, zlib24th6ptyb4ibzn3tj2cndqafs6rhm4ed4gruxztaaco35lka.b32.i2p

**Comment by tupaschoal** [comment]
Thanks for your contribution!
