### ISSUE TITLE
Update Internet Archive / Open Library

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#2015]
## Backstory

There are two ways to delete the account, instead of redirecting users to account page I think it's better to mention the official help page. Mail is not necessary but I think instead of  deleting your existing pages manually, mailing them for that could be the better option, so for us it's _medium_ level difficulty.

## Data

- `name`: Internet Archive / Open Library
- `url`: https://help.archive.org/help/how-do-i-delete-my-account/
- `difficulty`: medium
- `notes`: Click on your screen name in the top right-hand corner. Click on Account setting, enter your password to unlock modifying settings, click “Delete Account”. Your library pages will remain unless you remove them manually before deleting your account. OR send them an email to remove pages from their side.
- `email`: info@archive.org
- `email_subject`: 
- `email_body`: 
- `domains`: archive.org, web.archive.org, openlibrary.org

**Comment by tupaschoal** [comment]
Thanks for your contribution!
