### ISSUE TITLE
Requesting "Hindi" language translation to be added 

### ISSUE THREAD

**Issue by shivam-maurya-git** [jdm-contrib/jdm#2024]
I want to translate "Just Delete me " in Hindi.

**Comment by tupaschoal** [comment]
Hi @shivam-maurya-git , thanks for your interest! I have just added Hindi to our crowdin project, let me know if you have questions.

**Comment by shivam-maurya-git** [comment]
@tupaschoal  I am unable to access this project on Crowdin. Please take a look into the image.
![image](https://github.com/jdm-contrib/jdm/assets/74864959/7009b670-bc45-4b92-abaf-d9b6ffd88be6)

**Comment by tupaschoal** [comment]
Can you try again now of it works @shivam-maurya-git ?

**Comment by shivam-maurya-git** [comment]
@tupaschoal , I am able to access now. Thanks.
