### ISSUE TITLE
Problem in JDM Extension

### ISSUE THREAD

**Issue by shivam-maurya-git** [jdm-contrib/jdm#2032]
When I was using JDM extension in chrome. When I visited YouTube (https://www.youtube.com/), then I clicked on extension, it takes me to "https://justdeleteme.xyz/#www.youtube.com" where it said that no solution found, because extension matches the domain name of live website to URL  of a service in the "URL" section of that service in the json file.
No result found
![image](https://github.com/jdm-contrib/jdm/assets/74864959/103e4820-8a43-4b8b-93db-7b8d6889280d)
In json file "Youtube, gmail, google one, google pay" have URL value : myaccount.google.com, when I opened this page (myaccount.google.com), then I clicked extension, I got these result. 
![image](https://github.com/jdm-contrib/jdm/assets/74864959/d7e85b9c-ff8d-4098-9fc3-f2c39c6fe321)

I think I solution can be changing URL value of each service to their main website.

**Comment by tupaschoal** [comment]
Extension is not maintained by us, but here: https://github.com/fregante/jdm
