### ISSUE TITLE
Add BingX

### ISSUE THREAD

**Issue by Rockedf** [jdm-contrib/jdm#2037]
## Data

- `name`:  BingX
- `url`: [BingX](https://bingx.com/removeAccount/)
- `url_CODE`: 
- `difficulty`:  medium
- `notes`: There is no button to delete the account, you have to search with a search engine. Once you open the url and accept the terms and services our account goes into review. The account is deleted within 1 to 5 business days.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by Alexuty07** [comment]
Addressed by #2039

**Comment by tupaschoal** [comment]
Thanks for the submission!
