### ISSUE TITLE
Add distill.io

### ISSUE THREAD

**Issue by Rockedf** [jdm-contrib/jdm#2038]
## Data

- `name`: distill.io
- `url`: distill.io
- `url_CODE`: 
- `difficulty`: easy
- `notes`: It does not take many steps, just look for the button to delete the account and that's it.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by Alexuty07** [comment]
Addressed by #2039

**Comment by tupaschoal** [comment]
Thanks for the submission!
