### ISSUE TITLE
Add Temu

### ISSUE THREAD

**Issue by extremq** [jdm-contrib/jdm#2041]
## Backstory

Log into Temu and open your profile. Click on "Account security" and then select "Delete my account".

## Data

- `name`: Temu
- `url`: https://www.temu.com/bgp_close_account.html
- `difficulty`: easy
- `domains`: https://www.temu.com/
- `notes`: Log into Temu and open your profile. Click on "Account security" and then select "Delete my account".

**Comment by erfanghorbanee** [comment]
this was needed.
