### ISSUE TITLE
Add GNC

### ISSUE THREAD

**Issue by telqr** [jdm-contrib/jdm#2047]
## Backstory

Open a live chat -> Ask for agent -> Request account deletion. Put a random phone number if you need to.
It will take 7-10 days for it to process.

## Data

- `name`: GNC
- `url`: https://www.gnc.com/help/contact-us.html#chat
- `difficulty`: Easy
- `notes`: Open a live chat -> Ask for agent -> Request account deletion. Put a random phone number if you need to.

**Comment by tupaschoal** [comment]
I'm putting this as hard, since it requires contacting customer support.

**Comment by tupaschoal** [comment]
Thanks for your contribution!
