### ISSUE TITLE
Add Kyun!

### ISSUE THREAD

**Issue by nyuuzyou** [jdm-contrib/jdm#2059]
## Data

- `name`:  Kyun!
- `url`:  https://kyun.host/dashboard
- `difficulty`:  easy
- `notes`:  In the "Disaster Zone" field, click on the "Nuke account" button.
- `domains`:  kyun.host kyun.li kyun.network

**Comment by Kefaku** [comment]
additional domains:
* blog.kyun.host
* files.kyun.host
* status.kyun.host

**Comment by tupaschoal** [comment]
Thanks for your contribution!
