### ISSUE TITLE
Add Featurebase

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#2076]
## Data

- `name`:  Featurebase
- `url`:  https://help.featurebase.app/en/articles/8033192-how-to-delete-my-featurebase-account-organization-and-data
- `url_CODE`: 
- `difficulty`:  easy
- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:  featurebase.app, auth.featurebase.app

**Comment by Kefaku** [comment]
I found additional domains:
* developers.featurebase.app
* docs.featurebase.app
* help.featurebase.app
* status.featurebase.app

**Comment by tupaschoal** [comment]
Thanks for your contribution!
