### ISSUE TITLE
Add commiss.io

### ISSUE THREAD

**Issue by tddybears** [jdm-contrib/jdm#2081]
## Data

- `name`: commiss.io
- `difficulty`: Hard (might be impossible; haven't gotten a response in a while)
- `notes`: Contact support via chat portal -> Ask to delete your account -> Wait for response
- `domains`: https://commiss.io/

**Comment by tupaschoal** [comment]
How long has the "in a while" been @tddybears ? And have you verified that your account is still active in the meantime?

When the support doesn't answer and the account remains up, we put it up as impossible.

**Comment by tupaschoal** [comment]
Ping @tddybears

**Comment by tddybears** [comment]
> How long has the "in a while" been @tddybears ? And have you verified that your account is still active in the meantime?
> 
> When the support doesn't answer and the account remains up, we put it up as impossible.

Sorry for the delay.

And the account is 100% active. It's been maybe a month or so, not a single email, not even an automatic one saying they got my ticket request. Maybe impossible is the best way to set it unless something magically happens from now. I think the website is abandoned or something.

**Comment by tupaschoal** [comment]
Ok, I'll add it as impossible, then. If you ever hear back, do feel free to come here and update us
