### ISSUE TITLE
Add builtbybit.com

### ISSUE THREAD

**Issue by tddybears** [jdm-contrib/jdm#2083]
## Backstory

I've contacted builtbybit in Feb 2023 asking them to delete my account. They told me no, they don't delete accounts. Since then, I've logged in again to see if I'd be able to delete an account and they've recently added a delete button. According to their Terms, it appears that deleting does remove your data from the website after 30 days, if they deem your account "low risk". From their backups after six months. It appears to be automatic now, where previously it was deemed impossible even with contacting support. 

What's interesting is they say "you cannot ever return" to the website after deleting, and doing so will get you a ban. I'm not sure how they determine this if it's not to store the data and compare it with new accounts.

They used to go by the name MC-Market.

## Data

- `name`: builtbybit
- `url`: https://builtbybit.com/account/removal
- `difficulty`: Easy (?)
- `notes`: Login -> Account Details -> Settings -> Account Removal -> Delete account
- `domains`: builtbybit.com

**Comment by tupaschoal** [comment]
Thanks for your multiple contributions!
