### ISSUE TITLE
Update Perplexity

### ISSUE THREAD

**Issue by nyuuzyou** [jdm-contrib/jdm#2092]
## Backstory

In the "System" field, select "Delete Account" and confirm the action. All data will be permanently deleted 30 days after the account is deleted.

## Data

- `name`: Perplexity
- `url`: https://www.perplexity.ai/settings/account
- `difficulty`:  easy
- `notes`:  In the "System" field, select "Delete Account" and confirm the action. All data will be permanently deleted 30 days after the account is deleted.

**Comment by tupaschoal** [comment]
Thanks for your contribution!
