### ISSUE TITLE
Add fixer.io

### ISSUE THREAD

**Issue by tripplehelix** [jdm-contrib/jdm#2097]
## Backstory

Go to your account page, clicked 'delete account' at the bottom.

## Data

- `name`: Fixer.io
- `url`: https://fixer.io/account
- `difficulty`: Easy
- `notes`: Go to your account page, click 'delete account' at the bottom.
- `domains`: https://fixer.io/

**Comment by tupaschoal** [comment]
Thanks for the 3 recent submissions!
