### ISSUE TITLE
Add Whimsical.com

### ISSUE THREAD

**Issue by Vhivi** [jdm-contrib/jdm#2110]
## Backstory

Went to my account settings page and scrolled to the bottom, account deletion request button was at the bottom. After clicking, it said that a request had been submitted.

## Data

- `name`: Whimsical
- `url`: https://whimsical.com/account
- `difficulty`: easy
- `notes`: You will need to enter your e-mail address and then confirm by re-authenticating.
- `domains`: https://whimsical.com/

**Comment by tupaschoal** [comment]
Thanks for your contribution!
