### ISSUE TITLE
Add Seedbox.fr

### ISSUE THREAD

**Issue by Vhivi** [jdm-contrib/jdm#2114]
## Backstory

No action is required. Other than to stop paying for your subscription. More info in the notes.

## Data

- `name`: Seedbox
- `url`: https://wiki.seedbox.fr/index.php/Comment_Résilier_son_abonnement
- `difficulty`: easy
- `notes`: 
          There are two ways of cancelling your pack, depending on how you ordered your services:
          
          **Without automatic payment:**
          
          Simply ignore the reminders and the pack will be automatically deleted from our servers.
          No action is required on your part.
          Ignore the automatic reminders sent by our system.
          
          **With automatic payment:**
          
          ***It is imperative to cancel the automatic payment before the renewal of your service, no refund will be made.***
          
           - Log in to your PayPal account.
           - Click on Preferences at the top of the page.
           - Click on "My money", then on "Update" next to "My pre-approved payments".
           - Select the payment, then click Cancel
           - All you have to do is ignore the renewal calls issued by the system and your pack will be deleted automatically when it expires.

- `domains`: https://www.seedbox.fr

**Comment by tupaschoal** [comment]
Thanks for your contribution!
