### ISSUE TITLE
Add youlookfab.com

### ISSUE THREAD

**Issue by tddybears** [jdm-contrib/jdm#2127]
## Data

- `name`: youlookfab.com
- `url`: https://youlookfab.com/member/USERNAME/account/ = Replace "username" with the users login username
- `difficulty`: Easy
- `notes`: Login -> Profile Dropdown -> Profile -> Account -> Delete Your Account
- `domains`: https://youlookfab.com/

**Comment by tupaschoal** [comment]
Thanks for your contribution!
