### ISSUE TITLE
Add W3Schools

### ISSUE THREAD

**Issue by not-a-ethan** [jdm-contrib/jdm#2128]
## Backstory

Email `hello@w3schools.com` with the content `#deleteme`, as said in this [help page](https://support.w3schools.com/hc/en-gb/articles/14697964112402-How-can-I-delete-my-account)

## Data

- `name`: W3Schools
- `url`: https://support.w3schools.com/hc/en-gb/articles/14697964112402-How-can-I-delete-my-account
- `difficulty`: hard
- `notes`: 
- `email`: hello@w3schools.com
- `email_subject`: #deleteme
- `email_body`: #deleteme
- `domains`: w3schools.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
