### ISSUE TITLE
Update teespring.com

### ISSUE THREAD

**Issue by tddybears** [jdm-contrib/jdm#2129]
## Backstory

I logged in, contacted their bot and the bot said it can be deleted with some information and sent me the Google form below. 

## Data

- `name`: teespring.com
- `url`: https://forms.gle/T8LQEYdQrwRoTa469
- `difficulty`: Hard
- `notes`: Login -> Chat with bot -> Get form -> Fill out form
- `domains`: teespring.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
