### ISSUE TITLE
Add uvpn.me

### ISSUE THREAD

**Issue by tddybears** [jdm-contrib/jdm#2132]
## Data

- `name`: uvpn.me
- `url`: https://uvpn.me/support/#contactus
- `url_CODE`: 
- `difficulty`: Hard (Must contact)
- `notes`: Login -> Contact -> Submit a form -> Wait for a response
- `email`: support@uvpn.me
- `email_subject`: 
- `email_body`: 
- `domains`: https://uvpn.me/

**Comment by tupaschoal** [comment]
Thanks for your contribution!
