### ISSUE TITLE
Add exclusivecarregistry.com (Exclusive Car Registry)

### ISSUE THREAD

**Issue by 6377** [jdm-contrib/jdm#2139]
## Backstory

Go to Security session of your account and rolling down to Delete Profile and type CONFIRM and Click Delete account button, then a email will sent, click DELETE ACCOUNT button. However, cars that you uploaded will remain on the website.

## Data

- `name`: Exclusive Car Registry
- `url`: https://exclusivecarregistry.com/account/security
- `difficulty`: Easy
- `notes`: Click Profile icon -> Show Menu -> Security -> Delete Profile -> Type CONFIRM -> Click Delete account button -> Email Sent -> Click DELETE ACCOUNT button
- `domains`: https://exclusivecarregistry.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
