### ISSUE TITLE
Add CEEOL

### ISSUE THREAD

**Issue by ghost** [jdm-contrib/jdm#2160]
## Backstory
There is no deletion button anywhere. I looked through my account and nothing worked.
## Data
- `name`: Central and Eastern European Online Library
- `url`: There is no account deletion page available.
- `difficulty`: Impossible
- `domains`: [https://www.ceeol.com/](https://www.ceeol.com/)

**Comment by KienVu1504** [comment]
To request account cancellation & remove your personal information, please email to [info@ceeol.com](mailto:info@ceeol.com). 

Note: CEEOL will retain and use your information as necessary to comply with their legal obligations, resolve disputes, and enforce their agreements.

ref: https://www.ceeol.com/help/privacy-policy
