### ISSUE TITLE
Add UI to simplify entry

### ISSUE THREAD

**Issue by fregante** [jdm-contrib/jdm#2169]
On https://justdeleteme.xyz/#squareup.com, you will find a "Help make JustDeleteMe better" link that points to the repo home. This is not useful for users that are not very familiar with GitHub.

Maybe Google Forms can simplify input and export each line as JSON.

There might be other tools that just output JSON for the user to paste here.

**Comment by tupaschoal** [comment]
I think we could do something that is very straight forward using a forms-like solution, but my biggest concern would be not having a way to discuss the entry with the submitter, if they provided incomplete or unclear instructions.
