### ISSUE TITLE
Twitter tracking

### ISSUE THREAD

**Issue by sevengali** [jdm-contrib/jdm#217]
The twitter share button brings in tracking from Twitter.

https://github.com/jdm-contrib/jdm/blob/4a2fdbaafbf73c19c7a9a0bf1e05884023e234ce/_includes/footer.html#L7-L8

**Comment by PyroSamurai** [comment]
hmm you're right, I don't like that either. If the others agree, I can remove that one. The one at the top should still work fine. @tupaschoal @Nightfirecat

**Comment by Nightfirecat** [comment]
Agreed, let's get rid of that. Looks like another button with a link to `https://twitter.com/intent/tweet?text=Just+Delete+Me+-+A+directory+of+direct+links+to+delete+your+account+from+web+services.+http%3A%2F%2Fjustdeletme.xyz` should do the job of replacing the current included scripts.

**Comment by PyroSamurai** [comment]
Just having one at the top should be fine. I don't like duplication.
