### ISSUE TITLE
Add Filen.io

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#2176]
## Backstory

It's an encrypted cloud storage provider

## Data

- `name`: Filen.io
- `url`: https://drive.filen.io/#/account/settings
- `difficulty`: Easy
- `domains`: https://drive.filen.io https://filen.io

The deletion option is at the bottom of the second tab on the user settings page when logged in.

**Comment by tupaschoal** [comment]
Thanks for your contribution!
