### ISSUE TITLE
Add Qobuz

### ISSUE THREAD

**Issue by spftware** [jdm-contrib/jdm#2179]
## Backstory

It's an audio streaming/purchasing platform, and found deletion process in My Account

## Data

- `name`: Qobuz
- `url`: https://www.qobuz.com/profile/delete/confirmation/email
- `difficulty`: Easy
- `notes`: Requires email confirmation.
- `domains`: https://www.qobuz.com https://qobuz.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
