### ISSUE TITLE
Checkbox to easily track deleted sites

### ISSUE THREAD

**Issue by leethax666** [jdm-contrib/jdm#218]
It would be nice to check off sites as a delete my accounts from them

**Comment by tupaschoal** [comment]
Not sure I get what you mean. You want a checkbox to tick there just to
know that you went over that website already? And would you expect this to
be persistent?

**Comment by Nightfirecat** [comment]
Generally, I'd personally recommend you track your account credentials in a password manager, and simply delete the entries from your password manager after deleting your accounts with JustDeleteMe's (or another site's) instructions.

**Comment by tupaschoal** [comment]
I guess naking it persistent goes against our vouch for privacy and making it last only during the same page view is kind of useless, as you probably remember what you just dealt with.

I say we can close this issue.

**Comment by PyroSamurai** [comment]
Agreed.
