### ISSUE TITLE
Update browser extension (READMEs)

### ISSUE THREAD

**Issue by ldexterldesign** [jdm-contrib/jdm#221]
Related:

https://github.com/justdeleteme/justdelete.me/issues/731#issuecomment-289033604
https://github.com/jdm-contrib/jdm/issues/181

Hi,

Hope you're well

Thanks for software

Do we have access to the browser extension pages?:

If yes, can we get the READMEs (inc. links) updated to point to http://justdeleteme.xyz and/or http://github.com/jdm-contrib

If no, can we create new extension pages

Currently, both Chrome and Firefox pages are all over the shop with regards to attribution and it's very confusing, especially with the project migration

Let me know if you have any issues - happy to help

Hope to hear back

Keep up great work

Yours faithfully

**Comment by Nightfirecat** [comment]
@ldexterldesign This project is only forked off of justdelete\.me, we don't have any control over that repository.

**Comment by ldexterldesign** [comment]
Thanks for reply

Sorry if I wasn't clear

I'm not referring to repositories, I'm referring to the browser extension pages:

http://addons.mozilla.org/en-US/firefox/addon/where-to-delete-an-account
http://chrome.google.com/webstore/detail/just-delete-me/hfpofkfbabpbbmchmiekfnlcgaedbgcf

Cheers

**Comment by Nightfirecat** [comment]
Oh, I see. The latter (the Chrome Store addon) does have links back to the updated site and repository.

The former is currently very outdated and needs updating to work with current versions of Firefox anyway. That said, that's a good item to make sure to cover with jdm-contrib/justdelete.me-firefox-addon#4

**Comment by ldexterldesign** [comment]
> Oh, I see. The latter (the Chrome Store addon) does have links back to the updated site and repository.

FYI There's a website link that directs to http://justdelete.me ?:

<img width="228" alt="screen shot 2018-07-04 at 01 38 37" src="https://user-images.githubusercontent.com/1715809/42249346-0fa530fe-7f2b-11e8-88b7-72b888104d64.png">

> The former is currently very outdated and needs updating to work with current versions of Firefox anyway. That said, that's a good item to make sure to cover with jdm-contrib/justdelete.me-firefox-addon#4

Yea, read that issue tonight, thanks for the linkup

Cheers

**Comment by MikeRogers0** [comment]
I've just pushed an update to https://chrome.google.com/webstore/detail/hfpofkfbabpbbmchmiekfnlcgaedbgcf to use the correct domain / report for Website/Support site :) It should become live in ~30 minutes.

**Comment by ldexterldesign** [comment]
@MikeRogers0 

![giphy](https://user-images.githubusercontent.com/1715809/42271623-171522dc-7f84-11e8-8b35-ace3d6dcb840.gif)

**Comment by PyroSamurai** [comment]
We'll probably not be updating firefox ext repo for this problem. We're still figuring out what to do with it since the add-on format changed with FF v57. So we'll call this issue closed for now.
