### ISSUE TITLE
Airbnb

### ISSUE THREAD

**Issue by randymfournier** [jdm-contrib/jdm#223]
No Longer impossible, should be changed to 'Hard'. Your account can be deleted by contacting, although some pertinent information may remain, link is still relevant.

> To delete your account:
> If you want to permanently close and delete your account, contact us.
> 
> When you delete your account:
> 
> - We will verify your identity for security purposes before accepting the deletion request.
> 
> - You can’t reactivate, recover any data, or regain access to your account once it’s deleted.
> 
> - Any reservations you currently have as a host or a guest will automatically be canceled.
> 
> - We’ll start working on your deletion request after we receive it, but some of your data may remain in our systems if we are legally required, or while we are legally permitted, to retain it.
> 
> - Instead of deleting certain data, we may de-identify or disassociate it, such that it no longer appears associated with you. Some information, such as your reviews and messages you sent to other users, may still be visible to others.

**Comment by tupaschoal** [comment]
Nice, can you submit a pull request? Otherwise I'll do it later.

**Comment by tupaschoal** [comment]
Closed via #225
