### ISSUE TITLE
Add Cursor.sh

### ISSUE THREAD

**Issue by 825i** [jdm-contrib/jdm#2241]
## Backstory

You can delete your account immediately, but it is a bit hidden on their settings page. You must be logged in first.

## Data

- `name`: Cursor.sh AI
- `url`: https://www.cursor.com/settings
- `difficulty`: Easy
- `domains`: https://cursor.sh

You have to click the tiny little "Advanced" word which doesn't look like a link underneath the payment option. Then it reveals the "Delete Account" link.

It looks like this:

![image](https://github.com/user-attachments/assets/c01ec0ed-02de-49ab-97f2-5a4fef2075ed)

**Comment by tupaschoal** [comment]
Thanks for your contribution!
