### ISSUE TITLE
Update ASUS

### ISSUE THREAD

**Issue by basketshoe** [jdm-contrib/jdm#2256]
## Backstory

Had to delete account and sent an email to the address on your website (and ASUS website too), they instantly replied telling me the new process (even tho they are saying email is still fine, but I think you have to send 2 of them).

## Data

- `name`: ASUS
- `url`: https://privacy.asus.com/pi/global/privacy
- `difficulty`: easy
- `notes`: Go to the website, select your type of account and select which data you want to remove
- `email`: privacy@asus.com
- `email_subject`: Data Deletion Request
- `email_body`: Please delete my account registered with this email address.
- `domains`: https://account.asus.com/

**Comment by tupaschoal** [comment]
Thanks for your contribution!
