### ISSUE TITLE
Add [addictinggames.com]

### ISSUE THREAD

**Issue by shuvashish76** [jdm-contrib/jdm#2267]
## Data

- `name`:  addictinggames.com
- `url`:  https://www.addictinggames.com
- `url_CODE`: 
- `difficulty`:  Hard
- `notes`:  Fill their form for account deletion https://addictinggameshelp.zendesk.com/hc/en-us/requests/new and they'll contact you again through mail for confirmation before deleting it.
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by tupaschoal** [comment]
Thanks for your contribution!
