### ISSUE TITLE
Add ok.ru

### ISSUE THREAD

**Issue by Xiaoia8** [jdm-contrib/jdm#2283]
- `name`: OK
- `url`: https://ok.ru/regulations
- `difficulty`: easy
- `notes`: The “Delete profile” button is at the bottom of the page
- `domains`: https://ok.ru/

https://github.com/user-attachments/assets/079a6475-742a-4ab2-995c-ff78170b3cb6

**Comment by tupaschoal** [comment]
Thanks for your contribution!
