### ISSUE TITLE
Add Reg.ru

### ISSUE THREAD

**Issue by nyuuzyou** [jdm-contrib/jdm#2287]
## Data

- `name`:  Reg.ru
- `url`:  https://help.reg.ru/hc/ru/#request
- `difficulty`:  medium
- `notes`:  To deactivate an account in Reg.ru, send a request to the support service with the account's login.
- `domains`:  reg.ru; www.reg.ru; reg.com

**Comment by tupaschoal** [comment]
Thanks for your contribution!
