### ISSUE TITLE
Inconsistency of difficulty levels

### ISSUE THREAD

**Issue by c106208** [jdm-contrib/jdm#231]
I've noticed that the difficulty levels can be inconsistent sometimes, especially the medium level which could use a more clear definition. For example MailChimp and a few others are listed as medium while easy would be a much more accurate description of them as they allows you to fully delete your account from your settings, while some of them require contacting support through the website, can only be deleted in an app, require you to verify your identity in an automated email with a link in it, some of them keep user data or contributions after deletion. We should consider clarifying the definition of the medium difficulty, especially in regards to when you have to contact support through a website which would be a much better match for the hard difficulty, and when a website allows account to be reactivated within a certain time period (usually 30 days). 

Can we consider clarifying this difficulty level and potentially reclassifying quite a few things in it?

**Comment by tupaschoal** [comment]
These are the current descriptions
Easy - Simple process
Medium - Some extra steps involved
Hard - Cannot be fully deleted without contacting customer services
Impossible - Cannot be deleted

We tend not to see too many mediums, o admit, but I don't know how to rephrase. I tend to see it as:
Easy - push button 
Medium - push button, but requires lots of clicks
Hard - contact support
Impossible - cannot be deleted / keeps user data

How would you rephrase them ?

**Comment by c106208** [comment]
What I was saying it that there are quite a few mediums that should really be easy and hard (main thing was contacting support through the website was sometimes called medium).

I was considering a submitting a PR to fix it but wanted some input first.

**Comment by Nightfirecat** [comment]
It sounds like you're on the right track--I'd believe that there are some entries that aren't correctly ranked for their difficulty. We'd be happy to accept PRs for correcting those! :)

**Comment by c106208** [comment]
I'll get the PR in sometime soon.

**Comment by c106208** [comment]
What do you think about a class for things that are easy to delete, they call it deletion, but they still keep some public contributions? These don't seem like a good fit for medium but impossible seems like it shouldn't confuse sites that will never delete your account to those that keep some public data like posts.
