### ISSUE TITLE
Add cheezburger.com

### ISSUE THREAD

**Issue by uem-m** [jdm-contrib/jdm#2310]
- `name`: cheezburger.com
- `url`: https://cheezburgernetwork.wordpress.com/faq/#q14
- `difficulty`: Hard
- `notes`: Under "How do I delete my profile?" on the FAQ: "If you are sure you would like to delete your account, please write to us at [contactus@cheezburger.com](mailto:contactus@cheezburger.com). Please let us know the user name and email address attached to the account, along with the reason why you wish to delete the account."
- `email`: contactus@cheezburger.com
- `domains`: https://www.cheezburger.com/

**Comment by tupaschoal** [comment]
Thanks for your contribution!

(Pushed through #2313)
