### ISSUE TITLE
Add Hello Fresh

### ISSUE THREAD

**Issue by tripplehelix** [jdm-contrib/jdm#2331]
## Backstory

Searched in the FAQ on how to delete my account, found it hidden in the last answer after searching and clicking some links. You fill out a form then confirm your email, it then sets off some confetti to make you happy. However doing all this only sends a request.

## Data

- `name`: Hello Fresh
- `url`: https://privacy.hellofresh.com/data-privacy
- `url_CODE`: 
- `difficulty`: hard
- `notes`: You need to fill out the form, then confirm your email. Once done, a request will be made. Don't get distracted by the confetti.
- `domains`: hellofresh.com, hellofresh.co.uk

**Comment by tupaschoal** [comment]
Hello Fresh already had an entry, but I updated it to match your instructions, thanks!

**Comment by tripplehelix** [comment]
Ah, OK, it wasn't showing in .co.uk
