### ISSUE TITLE
Update Robinhood

### ISSUE THREAD

**Issue by mariosm1** [jdm-contrib/jdm#2333]
## Backstory
Tried to delete - live chat support said they can not delete or disable my login because they have to continue to allow me access to my records.  They do offer a self service option to delete marketing info they've collected.  They also allow you to delete individual accounts like your brokerage account but not your login.

## Data

- `name`: Robinhood
- `url`: https://robinhood.com/contact
- `difficulty`: impossible
- `notes`: Support will not disable / delete your login.  Individual brokerage or crypto accounts can be deleted as well as marketing information through self-service option.

**Comment by tupaschoal** [comment]
Thanks for your contribution!
