### ISSUE TITLE
Update Grubhub

### ISSUE THREAD

**Issue by mariosm1** [jdm-contrib/jdm#2334]
## Backstory

I sent an email requesting account deletion.  Support pointed me to this link which let me delete my account and data https://www.grubhub.com/help/privacy/manage-your-data

## Data

- `name`: Grubhub
- `url`: https://www.grubhub.com/help/privacy/manage-your-data
- `difficulty`: easy
- `notes`: Go to https://www.grubhub.com/help/privacy/manage-your-data.  Click to submit a request under "Delete your personal information".

**Comment by tupaschoal** [comment]
I put it as medium, since these requests are usually manually processed. Let me know if it was instantaneous and I can update.
