### ISSUE TITLE
Humble Dumble

### ISSUE THREAD

**Issue by Pucci00** [jdm-contrib/jdm#238]
Can’t find a way to delete my Humble Dumble account and link is not in the jdm library

**Comment by tupaschoal** [comment]
I'm guessing you meant humble bundle. Did you contact them? That way we can differentiate between a 'hard' and an 'impossible'

**Comment by Pucci00** [comment]
They wrote me this, I don’t know if you will consider it as impossible:

“Due to security concerns, customers are unable to delete their Humble Bundle on their own. However, we are happy to help with this action. Simply ensure that you have included 3 or more transaction IDs from previous orders associated with your account and we will follow up to delete the account.
[Finding Your Humble Transaction ID](https://support.humblebundle.com/hc/en-us/articles/202556850-Finding-Your-Humble-Transaction-ID)”

**Comment by tupaschoal** [comment]
It is hard, impossible is when deny it completely or just deactivate, but keep the data. I was actually submitting the PR as you replied. Will just update with the info you provided.

**Comment by Nightfirecat** [comment]
How did you contact Humble Bundle support? That's one piece of information I'd like to include in the entry before adding it.

**Comment by PyroSamurai** [comment]
Sounds like they won't let you delete your account if you haven't bought three items from them. That's messed up.

**Comment by Pucci00** [comment]
I contact them in the section “submit a request” at https://support.humblebundle.com

**Comment by tupaschoal** [comment]
I don't know @PyroSamurai , if we can expect them to be reasonable, I'm pretty sure they would open an exception in this case.

**Comment by Pucci00** [comment]
@tupaschoal , they finally wrote me this:

“As requested, I have deleted your Humble Bundle account.
We're sorry to see you go, but feel free to come back anytime! You can create an account in the future under the same email address which will reclaim any previous orders, and you can still make purchases without an account.”

If creating an account with the same email address will reclaim the orders, is it like if they have deactevated my account rather than cancelled it?

**Comment by tupaschoal** [comment]
Seems very likely, so I will change the difficulty to impossible.
