### ISSUE TITLE
Desktop.ly does not exist any more

### ISSUE THREAD

**Issue by luontokoodaus** [jdm-contrib/jdm#242]
You can't access the site any more because it's been shut down so you also cannot delete your account. It should be removed from the site.

**Comment by tupaschoal** [comment]
Thanks @luontokoodaus !

I created a PR for each of the issues you opened.

**Comment by luontokoodaus** [comment]
There's a lot more sites. I'll get around to mentioning them all and this time I'll do it all in one issue, but thanks!

**Comment by tupaschoal** [comment]
Ok, just one tip, there is no need to close the issues yourself, when the pull request is accepted, we close them automatically :)
