### ISSUE TITLE
Please add Keybase.io

### ISSUE THREAD

**Issue by luontokoodaus** [jdm-contrib/jdm#259]
[Keybase.io](https://www.keybase.io)

Delete account link: https://keybase.io/account/delete_me

Should be green, they allow deleting your account in seconds. Maybe mention on site though that you will never be able to re-register that username ever again.

**Comment by Nightfirecat** [comment]
Hm... If the username cannot be re-registered, it sounds like they do store some information of the user after account deletion?

**Comment by luontokoodaus** [comment]
They have stated that no user data is kept at all, only that the username registered was deleted and therefore it will not be able to be used again. In short, they have only a list of previously registered, but now closed **usernames**. Nothing more.

**Comment by tupaschoal** [comment]
I've written a PR, please take a look to see if you find it fit.
