### ISSUE TITLE
Native names of languages

### ISSUE THREAD

**Issue by GrimPixel** [jdm-contrib/jdm#264]
It's not “中国的”, it's “简体中文”.

**Comment by GrimPixel** [comment]
Not only Chinese. There are also other incorrect ones.

**Comment by tupaschoal** [comment]
I've written a PR to fix it. Thanks for reporting!

@GrimPixel could you also mention the other languages you found are incorrect?

**Comment by GrimPixel** [comment]
In Wikipedia, they are written as:

Arabic - العربية
Catalan - Català
German - Deutsch
English - English
Spanish - Español
Farsi - فارسی
French - Français
Indonesian - Bahasa Indonesia
Italian - Italiano
Dutch - Nederlands
Polish - Polski
Portuguese - Português
Romanian - Română
Russian - Русский
Slovak - Slovenčina
Serbian - Српски
Thai - ไทย
Turkish - Türkçe
Vietnamese - Tiếng Việt
Chinese - 中文

Some languages actually don't have a capitalized initial letter in their native names.

**Comment by tupaschoal** [comment]
Thanks, I've double checked all of them and update some in #268 .
