### ISSUE TITLE
Translations files contain duplicated strings and HTML tags for "guide" and "extensions" keys

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/jdm#275]
In the below JSON taken from en.json, the following keys contain duplicated information and encoded HTML tags which can likely be moved out into template files instead.

```
    "extensionl1": "<span class=\"dot-wrapper\"><span class=\"dot easy\"></span></span> - Simple process",
    "extensionl2": "<span class=\"dot-wrapper\"><span class=\"dot medium\"></span></span> - Some extra steps involved",
    "extensionl3": "<span class=\"dot-wrapper\"><span class=\"dot hard\"></span></span> - Cannot be fully deleted without contacting customer-services",
    "extensionl4": "<span class=\"dot-wrapper\"><span class=\"dot impossible\"></span></span> - Cannot be deleted",
    // ...
    "guideeasy": "<span class=\"difficulty\">Easy</span> - Simple process",
    // ...
    "guidehard": "<span class=\"difficulty\">Hard</span> - Cannot be fully deleted without contacting customer services",
    "guideimpossible": "<span class=\"difficulty\">Impossible</span> - Cannot be deleted",
    "guidemedium": "<span class=\"difficulty\">Medium</span> - Some extra steps involved",
```

(this issue is mostly a reminder to myself to look into later)

**Comment by Nightfirecat** [comment]
As far as I can see, the extension doesn't reference translation files at all, and these keys are only used in the template page. ([1](https://github.com/jdm-contrib/jdm/blob/master/_includes/body.html#L72-L75), [2](https://github.com/jdm-contrib/jdm/blob/master/_includes/body.html#L92-L95)) Based that on that understanding, I don't see any reason the text that's shared between the keys needs to be duplicated.

**Comment by PyroSamurai** [comment]
Well feel free to experiment, just don't leave things broken if anything breaks as a result :)

**Comment by Nightfirecat** [comment]
Another thing I hope to achieve with fixing this is removing discrepancies between the "Guide" and "Extension Dot Guide" sections on the site, where the phrases should be identical between them but aren't because of contributions over time which may have updated only one of the sections. (See the description for "Hard" in German for instance)

**Comment by PyroSamurai** [comment]
I see. Good point.

**Comment by Nightfirecat** [comment]
Forgot to comment here, but I didn't end up going through with this because I quickly noticed that there are actually a fair number of discrepancies between the sections in spite of the shared text, dating back to the site's origins. I don't have the insight or knowledge needed to determine for each case of each language which one is "more correct", so I've left it be for now. While I'd like to unify these eventually, the tradeoff of work required to benefit gained is not high here.

**Comment by tupaschoal** [comment]
'Tis ok, should we close it?

**Comment by Nightfirecat** [comment]
I don't have strong feelings either way. It's still something I'd like to see fixed eventually, but it's unlikely to matter so it wouldn't be a big deal if it went unfixed.

**Comment by tupaschoal** [comment]
Up for grabs, if anyone is interested

**Comment by tupaschoal** [comment]
With #417, it became easier to compare the `extension*` and the `guide*` strings. Out of the 22 languages, 15 have the same text for both:

1. cat
2. en (one wasn't really equal, but the difference is a hyphen)
3. es
4. fa
5. fr
6. gr
7. id
8. it
9. pl
10. pt_br
11. ro
12. sr
13. th
14. zh-cn
15. zh-tw

Here are the ones that didn't with the original and the google translation of the differences:

## AR 
`    "extensionl1":"عملية بسيطة"`: "simple operation"
`    "extensionl3":"لا يمكن حذفه بصفة نهائية إلا عند الاتصال بالدعم",`: "It cannot be permanently deleted except when contacting support"
`    "guideeasy":"عملية سهلة",`: "easy operation"
`    "guidehard":"لا يمكن مسحه بصفة نهائية حتى تتصل بدعم الموقع",`: "Cannot be permanently deleted until you contact the site support"

## DE
`"extensionl2": "Einige zusätzliche Schritte sind nötig"`: "Some additional steps are necessary"
`"extensionl3": "Kann nicht vollständig gelöscht werden, ohne den jeweiligen Support zu kontaktieren"`: "Cannot be completely deleted without contacting the respective support"
`"guidemedium": "Einige zusätzliche Schritte sind notwendig"`: "Some additional steps are necessary"
`"guidehard": "Kann nicht gelöscht werden, ohne den jeweiligen Support zu kontaktieren"`: "Cannot be deleted without contacting the respective support"

## NL
`"extensionl3": "Kan niet volledig worden verwijderd zonder contact met de klanten service"`: "Cannot be completely removed without contacting the customer service"
`"extensionl4": "Kan niet verwijderd worden"`: "Cannot be deleted"
`"guidehard": "Kan niet volledig worden verwijderd zonder contact met de klantenservice"`: "Cannot be completely deleted without contacting customer service"
`"guideimpossible": "Kan niet worden verwijderd"`: "Cannot be deleted"

## RU
`"extensionl2": "Нужны дополнительные действия"`: "Need more action"
`"extensionl3": "Невозможно полностью удалить без обращения в службу поддержки"`: "Cannot be completely removed without contacting support",
`"guidemedium": "Необходимы дополнительные действия"`: "Extra action needed"
`"guidehard": "Нельзя полностью удалить без обращения в службу поддержки"`: "Cannot be completely removed without contacting support"

## SK
`"extensionl2": "Nutné kroky naviac"`: "Extra steps required"
`"guidemedium": "Nutné extra kroky naviac"`: "Extra extra steps required" (This one actually looks like a typo) ❗️ 

## TR
`"extensionl2": "Ilgili bazı ek adımlar"`: "Some additional related steps"
`"guidemedium": "Bazı ekstra işlemler"`: "Some extra actions"

## VI
`"extensionl1": "Đơn giản"`: "Simple"
`"extensionl2": "Cần thêm một số bước bổ sung"`: "Need some extra steps"
`"extensionl3": "Không xóa được nếu không liên hệ bộ phận dịch vụ khách hàng"`: "Cannot be deleted without contacting customer service"
`"guideeasy": "Chỉ cần một vài thao tác đơn giản"`: "Just a few simple steps"
`"guidemedium": "Cần có thêm một số thao tác bổ sung"`: "Some additional operations are needed"
`"guidehard": "Không thể xóa bỏ tài khoản hoàn toàn trừ khi có sự liên lạc với bộ phận chăm sóc khách hàng"`: "Cannot delete account completely unless contacted customer service"

### Conclusion
I know that Google Translate is not perfect, but it really looks like most of the differing ones are just using synonyms or paraphrasing one another, so I think we could go with merging to just having either all `extesionl` or `guide`. What do you say @Nightfirecat and @PyroSamurai ?

**Comment by Nightfirecat** [comment]
Good to hear these are mostly identical between "extension" and "guide" keys. (minus the SK translation :eyes:)
It may be worth using a second translation service to gauge which is a "better" translation, but either is likely just fine. Given that we're getting rid of the "extension" key in #417, I think the "guide\*" keys will be a better fit to store whichever translations we end up keeping.

**Comment by tupaschoal** [comment]
I updated the post above with comparison translations from Google Translate and Bing
