### ISSUE TITLE
Heroes of Newerth

### ISSUE THREAD

**Issue by roshavagarga** [jdm-contrib/jdm#296]
Does not offer any way or information on how to delete account and related information. May be possible through their support email, which when pinged creates a new account with a default password linked to the email used to ping it.

**Comment by tupaschoal** [comment]
You mean that if you delete an account and then use the same email linked to that previous account it just returns with a default password?

**Comment by roshavagarga** [comment]
I successfully deleted my account, by way of their support email.

Whether you do or do not have a registered account, if you send a message to their support email, a new account will be created for their support platform, featuring a randomly generated password and your email as the username. Whether it is automatically linked to your other account(s) remains to be seen.

Still, they offer no feature to delete it on your own, and I had to dig a bit to find the support email at all.

**Comment by tupaschoal** [comment]
Do you still have the email, so we can file a proper PR?

**Comment by roshavagarga** [comment]
If you mean their support email, it's support@heroesofnewerth.com

**Comment by tupaschoal** [comment]
Thanks, I'll write a PR later today

**Comment by roshavagarga** [comment]
Thank you for being so cordial and helping this project. It's been of great help for staying as secure as possible :)
