### ISSUE TITLE
500px

### ISSUE THREAD

**Issue by roshavagarga** [jdm-contrib/jdm#306]
Should be amended from 'Easy' to intermediate. The settings gives you the right to deactivate your account - not permanently delete it and any information that may or may not have been stored about you.

To delete it, you must follow the instructions here:
https://support.500px.com/hc/en-us/articles/360009701153-How-do-I-delete-my-account-

**Comment by tupaschoal** [comment]
I think it actually has to be moved to hard, as our hard says "cannot be deleted without contacting customer services"

**Comment by tupaschoal** [comment]
I created a PR with medium, anyway, we can change it later if need be.

**Comment by roshavagarga** [comment]
Whichever you consider, I did have to contact them via email to get everything deleted, waiting on a response.

**Comment by tupaschoal** [comment]
Hard it is, then. Thanks for the prompt feedback :)
