### ISSUE TITLE
Add note to sites that give SSL error

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#335]
While doing #333 I noticed several entries that yield an exception with invalid SSL certificate. I wonder if we shouldn't add a note to those, as they're particularly concerning if you're worried about privacy, What do you think @Nightfirecat and/or @PyroSamurai ?

**Comment by Nightfirecat** [comment]
I presume most sites which have invalid certs on their help sites likely also have invalid certs on the rest of the site as well, so I'm not sure that would be of much use.

**Comment by PyroSamurai** [comment]
I believe browser clients already warn people about invalid certs so I don't think we have spend effort warning them ourselves.

**Comment by tupaschoal** [comment]
Ok, thanks for the inputs :)
