### ISSUE TITLE
Add possibility to get JSON data as API request

### ISSUE THREAD

**Issue by xslim** [jdm-contrib/jdm#338]
For better integration with other platforms, can you please add possibility to request `sites.json` as API request?

Example would be a password manager that would query JDM to get the info on how to delete the account.

**Comment by Nightfirecat** [comment]
I'd be fine with us providing this. Thoughts? @tupaschoal @PyroSamurai

**Comment by tupaschoal** [comment]
If it's the whole `sites.json` seems ok, though I'm not willing to implement it myself :p

Are there any password managers that you're thinking about integrating it into or is it just wishful thinking?

**Comment by PyroSamurai** [comment]
plug away @Nightfirecat

**Comment by xslim** [comment]
I guess I could just pull the `https://raw.githubusercontent.com/jdm-contrib/jdm/master/_data/sites.json`
was thinking maybe for future something like `https://justdeleteme.xyz/sites.json` could be nicer

**Comment by PyroSamurai** [comment]
That's what the other people seeking to use our json file did [ddg api request](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3309).
That link you suggested isn't possible on a github site, direct linking without "raw" subdomain is not possible.

**Comment by Nightfirecat** [comment]
For the time being, I think that's the approach we'd recommend.
