### ISSUE TITLE
Mint is incorrect/outdated

### ISSUE THREAD

**Issue by nloveladyallen** [jdm-contrib/jdm#339]
I'd open a PR myself but it has to be localized.

How to delete your Mint account: Go to Settings, then Sign In & Security, then scroll down to "Delete your Mint account". Enter your email and password again and click "Delete".

**Comment by Nightfirecat** [comment]
If the process needs to be updated, you can remove the old localized versions. It's better for us to have an updated process only available in English than to have an older version available in multiple languages.
