### ISSUE TITLE
Update Spotify?

### ISSUE THREAD

**Issue by stevenmchoi** [jdm-contrib/jdm#345]
It seems like the flow of closing your account, both for premium and free users, has gotten signifcantly easier. They save your username in that it's unavailable to be used again, but it seems like all other information is deleted (after the 7-day grace period of reactivating your account).

Unless there's more to it than simply "closing" one's account and actually confirming that all the data on a user is deleted, maybe this should be updated to `easy`?

**Comment by tupaschoal** [comment]
Spotify was just recently modified to `hard`, on #327 . According to the reporter, it takes you several steps + chat with the support team to delete the account. Did you have a different experience?

**Comment by stevenmchoi** [comment]
Huh, interesting. Yeah, I had a very different experience from what was last committed. Maybe @jtagcat can help verify it?

**Comment by jtagcat** [comment]
Well what I wrote was true. Had a Premium **trial**.

**Comment by tupaschoal** [comment]
What was the experience you had @stevenmchoi?
Cause we assign `easy` for the ones that are a push button away

**Comment by stevenmchoi** [comment]
So I tried it out again by creating an account with my old email and got the same thing. I had no playlists or followers or saved songs, and my username had changed, since it's a new account and usernames can't reused. I also tried it with my own account up until the last step.

My experience: I went to http://support.spotify.com/close-account and it took me through a 5-part flow, with the fourth step being an email verification link, and the fifth being the confirmation text. For my own personal Premium account, there were 4 parts, but I was only willing to go up to Part 3 for it.

Here's what I wrote for a possible change:
```
    {
        "name": "Spotify",
        "url": "http://support.spotify.com/close-account",
        "difficulty": "easy",
        "notes": "Go to the provided link and simply go through the flow, which, for a free account, concludes by clicking a link in a verification email. Username, playlists, and followers will no longer be available. You may reactivate your account within 7 days.",
        "domains": [
            "spotify.com"
        ]
    }
```

Here are some screenshots:

# Free account:
<img width="1190" alt="free1" src="https://user-images.githubusercontent.com/7029300/65556133-785fd680-dee3-11e9-8c28-68c3ae7f0b45.png">
<img width="933" alt="free2" src="https://user-images.githubusercontent.com/7029300/65556134-785fd680-dee3-11e9-8271-39e01fff5159.png">
<img width="1145" alt="free3_1" src="https://user-images.githubusercontent.com/7029300/65556135-785fd680-dee3-11e9-81b5-a09a49660af0.png">
<img width="1157" alt="free3_2" src="https://user-images.githubusercontent.com/7029300/65556136-78f86d00-dee3-11e9-9936-3b2dbb181b67.png">
<img width="1173" alt="free4" src="https://user-images.githubusercontent.com/7029300/65556137-78f86d00-dee3-11e9-912a-a9711087cdbf.png">

## Verification email
<img width="460" alt="free4email" src="https://user-images.githubusercontent.com/7029300/65556138-78f86d00-dee3-11e9-93e1-94e7808cad69.png">
<img width="1159" alt="free5" src="https://user-images.githubusercontent.com/7029300/65556139-78f86d00-dee3-11e9-9396-17ee6bdbb7f0.png">

## Confirmation email
<img width="503" alt="free5email" src="https://user-images.githubusercontent.com/7029300/65556140-79910380-dee3-11e9-833b-21328d3a82d9.png">

# Premium account (I was only willing to go as far as Step 3 for this one):
<img width="1033" alt="premium1" src="https://user-images.githubusercontent.com/7029300/65556141-79910380-dee3-11e9-8839-75572227fe1e.png">
<img width="1030" alt="premium2" src="https://user-images.githubusercontent.com/7029300/65556142-79910380-dee3-11e9-920e-65f618f2e963.png">
<img width="1031" alt="premium3" src="https://user-images.githubusercontent.com/7029300/65556143-79910380-dee3-11e9-89cb-3845739cb50e.png">

Let me know if I might be a different case.

**Comment by tupaschoal** [comment]
I think that's enough proof, thank you for doing this, maybe @jtagcat incurred in a special case as his was a trial account?

I think you can write a PR changing it to medium, because though the steps are simple, it is still a multi-step process, now not requiring human interaction

**Comment by jtagcat** [comment]
Maybe, but the chat opened after the link you have there. I'll look in to reproducing with a real premium account. If anyone feels donating a spotify account (I can back up everything with my Soundiiz account), let me know in few days.

**Comment by tupaschoal** [comment]
@jtagcat did you get any different result? Otherwise we might want to follow-up with @stevenmchoi 's suggestion

**Comment by stevenmchoi** [comment]
@tupaschoal Thanks for doing this!
