### ISSUE TITLE
JHM / JSM - "JustHelpMe" / "JustSupportMe"?

### ISSUE THREAD

**Issue by stevenmchoi** [jdm-contrib/jdm#346]
I love the UI of JDM and how accessible all the info is, and I thought about how it might be applied to other "dark pattern"-ish areas.

I know there are others doing this idea, but what about finding the best solution for support from a helpdesk? Providing/fetching/pointing to their phone number, email address, chat links, etc., and, if needed, grouped by department within the company. And maybe the most recommended option to use, what people have had the most success with, pros and cons of each, who uses bots and copy/paste messages to answer problems, etc.?

I suggest this because sometimes it's just as hard to find real people to help with an issue as it is to figure out how to delete an account. Let me know what you think!

**Comment by tupaschoal** [comment]
I feel your pain, I've been into lots of these quests to try to find someone to talk to. I personally like the idea, even started to build a site I called [PasswordInfringers](https://github.com/tupaschoal/PasswordInfringers) where I would list websites that save your pass as plain text. I never followed up though.

It's ok, for me, if you want to build a "JHM/JSM" based of "JDM", I might even contribute sometimes. What is it that you propose?

1. JDM repo to expand and become something more.
2. JDM org to expand and host more "just ..." services
3. JDM team to help you on deploying this new repo
4. JDM team to help you on defining the idea/scope

**Comment by stevenmchoi** [comment]
(on PasswordInfringers) Huh, that would be really useful if we knew of a way to confirm these companies! Awesome idea! (maybe "JustProtectMe" / "JustEncryptMe"? ¯\_(ツ)_/¯)

Thanks! I don't think, at this time, I'll be able to maintain a team or open source project of my own, so, if anyone wants to use my idea, it's totally up for grabs! I might contribute occasionally too. My original idea was number 2, since I didn't think helpdesk stuff would go under the "Delete" category; I also think it's kinda catchy 😄

**Comment by tupaschoal** [comment]
> (on PasswordInfringers) Huh, that would be really useful if we knew of a way to confirm these companies! Awesome idea! (maybe "JustProtectMe" / "JustEncryptMe"? ¯_(ツ)_/¯)

I usually find out when I sign up, because I immediately click "forgot my password", and from there you know what happens.

> My original idea was number 2
I don't feel like I've experienced this enough, I will leave the issue open if anyone is willing to start it.
