### ISSUE TITLE
Account deletion at some websites

### ISSUE THREAD

**Issue by SnwMds** [jdm-contrib/jdm#349]
<h3 align='center'>Currently situation</h3>

In the last 3 months I have been trying to request the deletion of my account on some online services that I no longer use, but it was unsuccessful.

The services are:

* [Freenom](http://freenom.com) (Offers free and paid services related to domain registration. Acts worldwide.)
* [textPlus](http://textplus.com) (Offers free and paid services related to online phone calls and SMS. Acts worldwide.)
* [Muambator](http://muambator.com.br) (Offers free and paid package tracking-related services. Something like the [17track.net](http://17track.net). Acts officially in Brazil, but can be used by users from other countries.)

I have read the Privacy Policy and Terms of Use of these services, but have not found any relevant information regarding permanent account closures and/or deletions. So I tried to request the deletion of my account directly through the contact forms specified by the online services.

<h3 align='center'>Contact</h3>

I tried to contact Freenom and textPlus customer support via email at:

* [info@freenom.com](mailto:info@freenom.com) (Freenom)
* [support@textplus.com](mailto:support@textplus.com) (textPlus)

Muambator doesn't provide a email address for contact, so I have make my request through the contact form at:

* [Muambator - Contact](http://muambator.com.br/contato/muambator)

My request sent was always the same:

_"I have no further interest in using the services provided by [ServiceName], so I want my account to be permanently deleted. My account ID is [AccountEmail]."_

I sent this same message about 2 ~ 4 times in a period of 3 months.

<h3 align='center'>Result</h3>

All my requests seem to have been completely ignored. I have received no response from customer support of these online services and my accounts are still active. No data was deleted.

**Comment by SnwMds** [comment]
Based on this information, should I then consider that it is impossible to delete an account in these online services? My requests have been ignored. These services also do not provide any relevant information about account deletions.

**Comment by tupaschoal** [comment]
I'd say so, yes. `Hard` is when it requires you to contact customer support, but you can actually achieve it in the end. `Impossible` is when they deny it or ignore.

**Comment by SnwMds** [comment]
Right, @tupaschoal. I will create a Pull Request to add these new websites to the list.
