### ISSUE TITLE
You CAN delete Slashdot accounts!

### ISSUE THREAD

**Issue by denterwiser** [jdm-contrib/jdm#397]
I am not a coder, so I don't know how to do this on my own:

You CAN delete your Slashdot account (I investigated after consulting JustDeleteMe.xyz). Refer to this page: https://slashdot.org/faq

>  You can delete your account by emailing feedback@slashdot.org from the email associated with your account. 

Just wanted to help! Sorry that I don't know how to propose the changes myself!

Keith

**Comment by tupaschoal** [comment]
Don't worry @denterwiser , you're already helping by telling us the up-to-date information, thanks :)

**Comment by denterwiser** [comment]
> Don't worry @denterwiser , you're already helping by telling us the up-to-date information, thanks :)

OK good! I'm glad this is the right way to do this.

I'm going to be going through other accounts of mine from the distant past and I'll be sure to cross-reference their published procedures against your website.

**Comment by tupaschoal** [comment]
Great, that will be awesome :)
