### ISSUE TITLE
Cleanup or make use of unused translated text

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#414]
I found out that there are some unused string resources in our translation files. I've labeled as ❌ to remove, ➕ to extend usage and ❓ what I need input on.

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L40

❌ Seems to be a former e-mail suggestions feature. We have decided in the past (#170, #280) not to accept any type of contribution other than PRs, so I think we can clean it up.

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L32

❌ Seems related to the e-mail submission as above.

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L26
https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L35-L36

❓ These three seemed to be ideas to link to contributors. Do we want to add it or just remove?

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L24

❌ Seems related to the translation above

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L9

➕ This is actually used at the explanation on the bottom, but I was thinking about extending it's usage to the big button at the top, which is currently always in English. 

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L3

❌ Seems an outdated and unused version of the `tagline`

> https://github.com/jdm-contrib/jdm/blob/9f1395cad0bf5a7b7403a659a3129660febec65a/_data/trans/en.json#L2

❌ At some point the site might have had an "ad" for the extension, which doesn't seem to exist anymore.

**Comment by Nightfirecat** [comment]
I agree with all of your conclusions here. Thanks for going through these with a fine-tooth comb.
