### ISSUE TITLE
Add AliExpress

### ISSUE THREAD

**Issue by paulaime** [jdm-contrib/jdm#431]
I know there's already Alibaba, so I don't know if the process is the same, but I saw Alibaba is listed as hard, while deleting an AliExpress is pretty easy.

Name: AliExpress
URL: https://accounts.aliexpress.com/user/organization/deactive_account.htm
Difficulty: Easy
Notes: To delete your account, just go to your "My AliExpress" page then click on the "Account Settings" then "Edit Settings" then choose the "Edit Member Profile" then click on the "Deactivate Account" button. When you are  on the Deactivation page, you can see there the option "Release my account at the same time" which means if you click on "Yes" your account will be deleted and all the data will be permanently deleted.

**Comment by tupaschoal** [comment]
Thanks for reporting!
