### ISSUE TITLE
Help wanted: ViaBox, Rosetta Stone

### ISSUE THREAD

**Issue by gracjankn** [jdm-contrib/jdm#434]
Does anybody know how to remove accounts on [Rosetta Stone](https://totale.rosettastone.com/sign_in) or [ViaBox](https://www.viabox.com/logins.php)?  🤔

I created these a long time ago for nobody knows what reason, and I could not find any way to delete them. 😞

If you know of such way, please add these websites to the services list and reply back to this issue with a link to a corresponding pull request, so I can finally get rid of them. 🙏🏻

**Comment by tupaschoal** [comment]
Hello @gracjankn ,

We usually use issues to add websites that people found out how to, but don't know how to do a PR. We tend not to do investigative work, because if the site doesn't allow for deletion, then ourselves will be left with one more account :)

That being said, I found [instructions for Rosetta Stone](https://support.rosettastone.com/en/language-learning/articles/How-to-deactivate-my-Rosetta-Stone-program/) on the first page of a Google search, can you see if they're applicable, so we can add them?

As for Viabox, I didn't find any. When there's no easy button or tutorial, it usually involves mailing them to request for deletion. Do mail them, if they don't reply within a handful of days, we deem it impossible, otherwise we rank it accordingly.

**Comment by gracjankn** [comment]
I checked this link — it isn't a correct answer. I looked at the privacy policy and they say to email them at privacyofficer@rosettastone.com with data-related questions, so I asked for account deletetion. I'm waiting for a response.

ViaBox is very tricky, but I found a contact form at [ViaBox Costumer Support](https://viabox.zendesk.com/hc/en-us/requests/new). It doesn't have a category like "data" or "privacy or "account issues" or anything like that, but I tried sending the request as a general question (default category). I'm also waiting for a response.

**Comment by tupaschoal** [comment]
Alright, let's give them a week to answer you, otherwise we update as impossible. If they ever get back to you after that, we can just correct the entries

**Comment by tupaschoal** [comment]
Did you hear back from any of them?

**Comment by tupaschoal** [comment]
Did you hear back from any of them @gracjankn ?

**Comment by gracjankn** [comment]
I did. The guys from ViaBox removed my account for the service itself, but I still have this other account for the support site. I wrote to them yesterday to delete it too and I'm waiting.

Regarding Rosseta Stone, they told me to submit a request through a form. They send me two links to for that.

For most people: https://app.onetrust.com/app/#/webform/f1e6ce28-8f84-4cae-9bdd-bc40113d5ee0
For California residents (different privacy law): https://privacyportal-cdn.onetrust.com/dsarwebform/27aac3ab-c36e-4457-81d4-9773ba27887e/a4611d02-cd40-4c80-8efb-af97324e0cc4.html

I did submit it using the first one, but now I see I needed to confirm the email address (which I didn't do). I will redo it now.

**Comment by tupaschoal** [comment]
> I did. The guys from ViaBox removed my account for the service itself, but I still have this other account for the support site. I wrote to them yesterday to delete it too and I'm waiting.

Was it required for you to create an account on support to request for deletion?

> I did submit it using the first one, but now I see I needed to confirm the email address (which I didn't do). I will redo it now.

Alright. For both of the entries, please collect the support email or link to support so we can update properly when we're at it. Thanks!

**Comment by gracjankn** [comment]
For ViaBox the case  is solved. You can the information I provided (the Zenbox link).

I’m still waiting for a response from Rosseta Stone to my resubmitted case.

**Comment by tupaschoal** [comment]
I've filed a PR to add ViaBox, when we get the Rosseta Stone info we'll do the same.

**Comment by tupaschoal** [comment]
Are you still waiting on Rosetta stone @gracjankn ?

**Comment by tupaschoal** [comment]
Hello @gracjankn, any news?

**Comment by gracjankn** [comment]
Yes, sorry. I was still waiting for an email from them, but now I had a thought. I tried to sign in to the Rosetta Stone website and it doesn’t accept my credentials. Reset password option also seems to not work. It seems, they removed my data silently (without email followup after process is completed). You can add both websites to the list and close the ticket.

**Comment by gracjankn** [comment]
@tupaschoal Have you seen my comment? I wrote, that you can add the Rosetta Stone to the list.

**Comment by tupaschoal** [comment]
Yes, but I can't do it at the moment
