### ISSUE TITLE
Photobucket no longer provides account deletion links

### ISSUE THREAD

**Issue by CarbonaraJack** [jdm-contrib/jdm#439]
Hello, I tried deleting my Photobucket account today, but I realised that with the new website redesign it is impossible to do so. The link provided by justdeleteme redirects to a login page that jumps the user to the new photobucket main page. I have searched for the functionality in the account settings but I couldn't find it. I believe that now it might be impossible to be eresad from photobucket.

**Comment by Nightfirecat** [comment]
Under the main page, after clicking on "Account status", is there a "Delete my account" link anywhere on that page?

**Comment by CarbonaraJack** [comment]
I think I was able to screenshot every single setting page, so you can see what I'm dealing with. The settings are quite a joke now.  
I was able to delete all my files manually and supply fake personal information, but I still couldn't find a way to delete my account.

This is the main page where you can upload your pictures.  
You are redirected here when you use the justdeleteme link. Clicking on your username does nothing.
![Screenshot 2020-02-13 at 17 14 49](https://user-images.githubusercontent.com/10898872/74414734-58768280-4e85-11ea-9c48-df235ff6ae6c.png)
Profile settings page
![Screenshot 2020-02-13 at 17 10 49](https://user-images.githubusercontent.com/10898872/74414718-5280a180-4e85-11ea-8d8a-b29c0722abe4.png)
Security settings page
![Screenshot 2020-02-13 at 17 12 48](https://user-images.githubusercontent.com/10898872/74414723-557b9200-4e85-11ea-9011-173cae001294.png)
Billing/plan landing page
![Screenshot 2020-02-13 at 17 13 13](https://user-images.githubusercontent.com/10898872/74414727-56142880-4e85-11ea-871a-34eb6f1b57ee.png)
Monthly billing
![Screenshot 2020-02-13 at 17 13 56](https://user-images.githubusercontent.com/10898872/74414730-57455580-4e85-11ea-8dec-783c941f9f5c.png)
Annual billing
![Screenshot 2020-02-13 at 17 14 28](https://user-images.githubusercontent.com/10898872/74414731-57ddec00-4e85-11ea-921a-6c36c3eceb8b.png)
And I think that's it. These are all the settings I could find

**Comment by tupaschoal** [comment]
Some websites require mailing them to delete the account, have you tried this? Maybe it's turned this harder

**Comment by CarbonaraJack** [comment]
> 
> 
> Some websites require mailing them to delete the account, have you tried this? Maybe it's turned this harder

Allright, good idea. I just mailed support, I will get back with their response as soon as I get one.

**Comment by tupaschoal** [comment]
Have you heard back from them @CarbonaraJack ?

**Comment by CarbonaraJack** [comment]
> Have you heard back from them @CarbonaraJack ?

Yes, just this morning. My account will be deleted in 48 hours.  
When first emailing them they ask you to provide this information

![image](https://user-images.githubusercontent.com/10898872/74794663-20e55b80-5307-11ea-84c2-98fd34482048.png)

Then after a couple of days you will get this

![image](https://user-images.githubusercontent.com/10898872/74794879-cb5d7e80-5307-11ea-9d41-fdef82f5713a.png)

So apparently they don't store your pictures after the account deletion.  
So yeah, I think we can label Photobucket as Hard.

**Comment by tupaschoal** [comment]
Do you have the support e-mail? Or did you file a request on a specific link?

**Comment by CarbonaraJack** [comment]
I mailed support@photobucket.com  
This was the body of my mail
![image](https://user-images.githubusercontent.com/10898872/74795534-92260e00-5309-11ea-91af-1c16c668fe50.png)

**Comment by tupaschoal** [comment]
Thanks! Feel free to write a PR now, otherwise I can do it tomorrow

**Comment by CarbonaraJack** [comment]
Alright, I will get to it later in the day.  
Thanks for the help :)
