### ISSUE TITLE
Statcounter

### ISSUE THREAD

**Issue by LRHALE** [jdm-contrib/jdm#441]
I'm not sure if it oughta be labeled easy or intermediate. It was kinda annoying to find because I had to search their support section, but once found, it was easy to do.

All you have to do is go to this link,
[https://statcounter.com/close_account.php](https://statcounter.com/close_account.php), and fill in your login info. It's reversible for 30 days, until your data gets purged.

**Comment by tupaschoal** [comment]
Well, if it's simply filling the form, sounds like easy. We take the hit of looking out for the info however difficult it is, so we made it simple for everyone else :P

Feel free to write a pull request now!
