### ISSUE TITLE
Add support for different URL for different languages?

### ISSUE THREAD

**Issue by GrimPixel** [jdm-contrib/jdm#458]
When a page is available in several languages, it is better to place corresponding versions' URL.

**Comment by tupaschoal** [comment]
I don't fully get what you mean, can you clarify?
The URL does change when you click another language, for example:
- `https://justdeleteme.xyz/de` for German
- `https://justdeleteme.xyz/it` for Italian

Did you mean this? Or did you expect the domain to change to `.de or .it`? Or did you expect the website to automatically capture your region and redirect?

**Comment by PyroSamurai** [comment]
I think he is saying that deletion url should act the same as the notes tag.

**Comment by GrimPixel** [comment]
OK, for example:
https://www.wg-gesucht.de/hilfe.html
https://www.wg-gesucht.de/en/hilfe.html
https://www.wg-gesucht.de/es/hilfe.html

They are different URL and can be associated with the German, English and Spanish version of JustDeleteMe.

**Comment by tupaschoal** [comment]
Hmm, I think it is fairly easy to support this. What's your take @PyroSamurai and @Nightfirecat ?

**Comment by PyroSamurai** [comment]
sounds fine.
