### ISSUE TITLE
Add to awesome?

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#469]
Would be a nice addition to [sindresorhus/awesome](https://github.com/sindresorhus/awesome)
Thoughts?

**Comment by tupaschoal** [comment]
I've seen this repo before and curiously enough, never thought about adding jdm, there. I find it a good idea, will you?

**Comment by jtagcat** [comment]
I don't know what category to add it under, miscellaneous, work, security, something else?

**Comment by tupaschoal** [comment]
I think "security" sounds ok, if they find it unsuitable, I'd go with "miscellaneous"

**Comment by PyroSamurai** [comment]
I'll protest if they don't let us in the security section lol (I secretly hate all the awesome repo stuff >///< )

**Comment by tupaschoal** [comment]
Did you do it @jtagcat ?

**Comment by jtagcat** [comment]
Not yet, I'll try to do it.
Everything I touch multiplies.
Closing one issue creates 5 more and so on.

**Comment by jtagcat** [comment]
In order for us to join the awesome cult, we need to add the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge). I made #474 to add it to the readme.

After we are granted awesomeness, I propose we add the badge to the site as well.

**Comment by PyroSamurai** [comment]
I'm against adding the badge to the actual site, it's a github thing like other badges.
Fulfillng the requirements by adding the badge to the readme should be enough.
Anyways, don't count your chickens before they hatch.

**Comment by tupaschoal** [comment]
> I'm against adding the badge to the actual site

I'm not very fond of it either, badges are useful for developers only and most of the users on the website aren't. If any of them is and get into the github, they'll see the badge on our `readme`.

Nice work on the PR description, btw :)

**Comment by jtagcat** [comment]
Removed badge on the site promise. My biggest concern is that the content isn't on the readme.

**Comment by tupaschoal** [comment]
On `README` we will merge as soon as the other PR goes through.

**Comment by PyroSamurai** [comment]
..... He denied PR, but I understand why. I thought you were putting us ON an awesome list, instead you were presenting us AS an awesome list.

**Comment by tupaschoal** [comment]
I thought too, well, then this can be closed. We can discuss on the issue of we find a list of awesome repos instead of a list of awesome lists.

**Comment by tupaschoal** [comment]
Well, I'll close this @jtagcat , if you find another list that we might be fit, please open a new issue.

Thanks for the effort in spreading JDM!

**Comment by jtagcat** [comment]
I agree, as I said before, I was concerned that it might not be an awesome list, but I still feel that it should be listed there.

¯\_(ツ)_/¯ could try to look in to the awesome lists listed on awesome, but I see my time used better.

**Comment by tupaschoal** [comment]
I understand :P
Thanks

**Comment by PyroSamurai** [comment]
See? If sindresorhus was smart, he'd add a search function for that overgrown list of his ;3 Like we have.

**Comment by jtagcat** [comment]
> See? If sindresorhus was smart, he'd add a search function for that overgrown list of his ;3 Like we have.

Why add it yourself, when others have done it for you: https://github.com/sindresorhus/awesome#related

**Comment by PyroSamurai** [comment]
ahahaha! That guy really has all the luck, doesn't he. I still have no idea why that list is popular.
