### ISSUE TITLE
Complete localization of website into already supported languages

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#493]
The language files in `_data/trans` were all updated to include more keys to be translated, that were previously hardcoded to English, and to remove HTML from the json, leaving it with just strings.

This made lots of strings in English pop-up in the language files and we'd like some help making sure they're tended to. Following is a checklist of languages that still need checking, if you are fluent in that language, please make a PR referring to this issue. Thanks!

It's recommended to open the English side-by-side with your language, as some English keys might have been updated over time.

- [ ] `ar.json`
- [x] `cat.json`
- [x] `de.json`
- [X] `en.json`
- [x] `es.json`
- [ ] `fa.json`
- [ ] `fr.json`
- [x] `gr.json`
- [x] `id.json`
- [x] `it.json`
- [x] `kr.json`
- [x] `nl.json`
- [ ] `pl.json`
- [x] `pt_br.json`
- [ ] `ro.json`
- [x] `ru.json`
- [x] `sk.json`
- [ ] `sr.json`
- [ ] `th.json`
- [x] `tr.json`
- [x] `ua.json`
- [x] `vi.json`
- [ ] `zh-cn.json`
- [ ] `zh-tw.json`

**Comment by sbritorodr** [comment]
#507

**Comment by tupaschoal** [comment]
@sbritorodr @AHOHNMYC @MarcCeleiro BraINstinct0 

These keys were just updated. `fork` became `contribute` and `forkproject` became `pullrequest`. This is their new text in case you want to update on the languages you translated:

- `"contribute": "Contribute on GitHub"`
- `"pullrequest": "Make a Pull Request on GitHub"`

Thanks :)

**Comment by jtagcat** [comment]
:/ did a double mention for `@AHOHNMYC`, made a really fancy _plz contribute_ at https://github.com/jdm-contrib/jdm/pull/542#issuecomment-645568525

**Comment by drfrostongithub** [comment]
Hi, is id.json is for Indonesian ? I can help for it, if it's yes.

P.S. Sorry this is my first time contributing on other's people repo :)

**Comment by tupaschoal** [comment]
To anyone listening out there, as of #1507 we have now generalized the extension sections to also mention our firefox extension, and your language might require updates. The changes are detailed on the collapsed section below:

<details>
  <summary><b>Translation changes for Firefox extension mentions</b></summary>

The extension text was renamed from `extension` to `extension_browser` and changed to mention both extensions:

```diff
-    "extension": "Google Chrome Extension",
+    "extension_browser": "Chrome/Firefox Extension",
```

Previous `extensionp1`, `extensionp2` and `mikerogers`, which formed a sentence crediting the author of the Chrome extension were removed to make the section generic to any browser extension:

```diff
-    "extensionp1": "Our good friend",
-    "extensionp2": "has helped us to release an awesome Google Chrome Extension for JustDeleteMe.",
-    "mikerogers": "Mike Rogers",
```

`extensionp3` was renamed `extensionp1` and changed to not mention the Chrome extension directly anymore:
```diff
-    "extensionp3": "When you are on a website that is listed on JustDeleteMe, the Chrome Extension will add a small dot to the omnibar. Clicking on this dot will take you to the relevant delete page.",
+    "extensionp1": "When you are on a website that is listed on JustDeleteMe, the extension will add a small dot to the omnibar. Clicking on this dot will take you to the relevant delete page.",
```

`extensionp4`, `extensionp5` and `extensionp6` were just renamed to `extensionp2`, `extensionp3` and `extensionp5`, respectively:

```diff
-    "extensionp4": "To install it, simply proceed to the",
-    "extensionp5": "Chrome Web Store",
-    "extensionp6": "",
+    "extensionp2": "To install it, simply proceed to the",
+    "extensionp3": "Chrome Web Store",
+    "extensionp5": "",
```

Finally, a new string was added as `extensionp4` to mention the Firefox Add-ons page:
```diff
+    "extensionp4": "Firefox Add-ons",
```
</details>

**Comment by MattiaRaffaele** [comment]
@tupaschoal i think you should add this project to [Crowdin](https://crowdin.com/)

**Comment by tupaschoal** [comment]
@MattiaRaffaele it's a good idea, I'm not sure about the effort though, will have to look into it when I have more time to spare.

**Comment by tupaschoal** [comment]
@MattiaRaffaele I've just added it to Crowdin, thanks for the suggestion. Took me a while to have some free time, but I think it will be helpful.

I'm closing this issue then, since Crowdin is a better way of managing updates, thanks everyone :)
