### ISSUE TITLE
Bluejeans

### ISSUE THREAD

**Issue by xhamyd** [jdm-contrib/jdm#512]
# Backstory
Hi all, I love this service and have been using it for months! I recently cancelled by Bluejeans account and wanted to contribute. After reading the contribution guidelines, I made the changes locally and successfully passed the tests. I was opening to open a PR with my branch, but unsure if I have correct permissions to contribute. Hoping that opening this issue is an acceptable way to contribute, apologies if I misread!

# Data
    {
        "name": "Bluejeans",
        "url": "https://support.bluejeans.com/s/contactsupport",
        "difficulty": "hard",
        "notes": "Contact support via the contact form and request deletion of your account. Only verified for cancelling a Bluejeans Meetings Trial.",
        "domains": [
            "bluejeans.com"
        ]
    },

**Comment by tupaschoal** [comment]
Hello @xhamyd ,

Yeah, of course opening an issue is acceptable, we want the site as complete as possible. Just to make it clear, you were so close, you just missed opening the PR hahah. Typically you won't have access to the main repository, like you said, so you just fork the repository, change what you want on a new branch of your fork and then submit a PR, to which we can reply/merge/etc.

**Comment by xhamyd** [comment]
Oh haha I see, so close! Wonderful, thanks for the help and the new PR!
