### ISSUE TITLE
Pluralsight 403

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#528]
So pluralsight.com/

They blocked my account because they couldn't verify my identity. Then they charged me.

I emailed with them and the end result being:
a) Give us all the personal data you have to verify that the account belongs to you (I already gave some payment information, as all other information on my account was already random stuff, that information should've been enough). After this we will refund and delete your account. I decided no, I'm not going to give you everything.
b) Support: I removed the payment method, will not delete the account (without a subscription the account is useless anyways, why keep it?), go ahead and dispute the charge with your bank (I will probably win, but why can't you just refund, if I dispute it will hurt your reputation with payment provider).

For me, without giving all the personal information I have (without them actually having any use for it), this makes account deletion impossible.
Since if your account isn't randomly picked to be blocked, the process is easy, I don't want to change it to impossible. At the same time, I feel 'easy' is not fair.

**Comment by tupaschoal** [comment]
`They blocked my account because they couldn't verify my identity.`

When did they require you to confirm your identity? Was it when you were already trying to delete it?

**Comment by jtagcat** [comment]
> `They blocked my account because they couldn't verify my identity.`
> 
> When did they require you to confirm your identity? Was it when you were already trying to delete it?

They used sparkly magic and unicorn blood to detect that my account was suspected in account sharing (yes I logged in from 2 different browsers total on day 1) (what is an ok concern from their point of view). I used it until day 2, came back later to delete the account, finding it blocked.

I still find it unreasonable to suspect account sharing on a trial account with 2 browsers from one ip, needing full suite of personal information in order to determine, that sharing is not the case (couldn't one person sharing the account with 2 people provide their own, defeating the purpose?) for account deletion. To continue using them, yes; but to delete, even remove payment method (latter they ended up doing, after putting up a fight).

**Comment by tupaschoal** [comment]
What about putting a `NOTE`, such as: "NOTE: If you have outstanding payments or disputes or if you aren't comfortable with sharing personal data to confirm deletion, it might be harder."

**Comment by jtagcat** [comment]
:thinking: Note would probably be the best resolution.. In my case, it might be impossible.

**Comment by jtagcat** [comment]
@tupaschoal just realized your profile picture.. Hello fellow (ATH-) M50xRD (dot) club (should buy the domain) member.
![IMG_20200613_192602_1](https://user-images.githubusercontent.com/38327267/84573950-23c2fb00-ad93-11ea-95c8-eaaf12202e3f.jpg)

**Comment by tupaschoal** [comment]
hahahaha cool! The earcups of mine are peeling off already :(

**Comment by jtagcat** [comment]
> hahahaha cool! The earcups of mine are peeling off already :(

Yeah I have a second pair, that I have indefinitely borrowed out, now fixed for the 3rd time.. https://www.reddit.com/r/headphones/comments/gvev4e/the_show_must_go_on/

**Comment by tupaschoal** [comment]
AMAZING :D
