### ISSUE TITLE
Contrib Guide missing translation detail

### ISSUE THREAD

**Issue by BraINstinct0** [jdm-contrib/jdm#536]
Guide file doesn't explain what `extensionp6` does(when translating).
Also it doesn't mention when to create new file/when to edit existing translation.
(e.g. first check if translation exists->then just edit the translation file. if not, do what's written there currently)

**Comment by tupaschoal** [comment]
@BraINstinct0 thanks for pointing that out, I always thought that it might be a problem, specially `extensionp6`, as it seems that some languages need to add text after the hyperlink.

I've added some explanations on a new file, check out the PR and let me know if something is still not clear.

**Comment by BraINstinct0** [comment]
Checked the PR, now it seems (mostly) complete!
Doesn't seems to have anything left out as of now.
