### ISSUE TITLE
Discourse

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#541]
Discourse is a platform, not a site.

It's pretty much impossible to delete your account, sometimes you can go anonymous (with post history retained), sometimes you can get it deleted by the mods. There isn't really information out there to say this, since there are many Discourse sites, I think we should do something about it.

**Comment by tupaschoal** [comment]
We had something similar in the recent past, where someone was opening multiple entries for something that was inherently the same thing/platform, but I don't recall the resolution now.

Do you remember @PyroSamurai and @Nightfirecat ?

**Comment by PyroSamurai** [comment]
@tupaschoal I think you are talking about the multiple domains thing. We just had them add all the possible domains and just the .com to url or something like that. Is that what you were thinking about? Btw, I have a discourse account that I use often if that is helpful.

**Comment by tupaschoal** [comment]
Yeah, I think that's right, we just its different domains on a same entry

**Comment by tupaschoal** [comment]
@jtagcat are there some services that you know use Discourse that we can list under an entry?

**Comment by jtagcat** [comment]
> @jtagcat are there some services that you know use Discourse that we can list under an entry?

restic rclone level1tech netlify syncthing are the first that come to my head

pretty much any larger open-source what's 'discuss on forum first'

**Comment by jtagcat** [comment]
I went to meta.discourse.org to ask for a list of their hosted instances. I got:
1. WTF NEW ACCOUNT LOL WHAT IS WRONG WITH YOU ASKING FOR INSTANCES HAHA, and a few emojis from a high rep user, who edited their comment a few times.
1. Some comment I didn't reach in time (see below)
1. Reply, that reached e-mail: "I’d be concerned if they would. You have no right to this information. The clients of a business you have no relationship to are private information."
1. Post deleted. Welp I guess the student union med student prompoter on meta.discourse.org was bored.

Facepalm. So I can pay google 2$ to do a wide search for `<meta name="generator" content="Discourse`, as all pages have a meta tag, for example `<meta name="generator" content="Discourse 2.6.0.beta1 - https://github.com/discourse/discourse version 544a9865c6e5890f37e762292cbe5558db843dcf">`. Ah yes, very private information you actively advertise on all pages.

**Comment by tupaschoal** [comment]
I appreciate the effort in going after all of these. We can only list more domains for the discourse entry, but domains are only picked up by the extension, so please test whether the extension is working for the ones we have provided, otherwise I don't think it's worth going after all of those, especially because there might be too many and we won't know if all of them are really used or active.

**Comment by jtagcat** [comment]
https://discourse.gohugo.io offers account deletion, and I successfully deleted with easy difficulty. Interesting, is this a plugin or a feature in a new version of Discourse. Investigation needed.
