### ISSUE TITLE
A-Z Sort on Website Misbehaving

### ISSUE THREAD

**Issue by MetalNeo** [jdm-contrib/jdm#554]
The dropdown menu to sort by letter doesn't seem to be working correctly. Instead of displaying websites whose name starts with the letter selected, the page will display websites where the second character in the name matches the letter instead.

For example, Zynga shows up when selecting "y," but not when selecting "z."

**Comment by tupaschoal** [comment]
Indeed, I'll look into it.

**Comment by tupaschoal** [comment]
Should be fixed now @MetalNeo !

Thanks for the reporting, I think this has been buggy since the very beginning and no one ever noticed, so congrats! hahahah

**Comment by PyroSamurai** [comment]
lol We sure did miss it. Skippy.
