### ISSUE TITLE
SaschaMoser Blog returning 404

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#580]
#436 added this entry which is [now returning 404](https://travis-ci.org/github/jdm-contrib/jdm/jobs/706378395), I noticed that clicking on "blog" redirects to `https://xopsblog.de/`. Should we delete this entry, update it or what else?

Wanna chime in @xopez ?

**Comment by xopez** [comment]
Hey, thanks for mention. I moved the domain to another. The content isnt changed. I will fo a pull request to change this here in a few days.
