### ISSUE TITLE
CONTRIBUTING.md not covering keys like notes_CODE in site info

### ISSUE THREAD

**Issue by BraINstinct0** [jdm-contrib/jdm#589]
In `_data/sites.json`, there are many entries with keys like notes_pt_br, notes_fr, notes_cat, etc.
Those seem to be the notes that are shown when using language-specific [jdm](justdeleteme.xyz)  sites.
I'm not sure if this should be covered in adding/editing site entries or the [Translation](https://github.com/jdm-contrib/jdm/blob/master/CONTRIBUTING.md#translation), but probably it should be noted in both.

**Comment by tupaschoal** [comment]
[Translation](https://github.com/jdm-contrib/jdm/blob/master/CONTRIBUTING.md#translation) is more about the translation of static strings used in the website.

I'll add a note (no pun intended) about them in contributing
