### ISSUE TITLE
Add Mathway

### ISSUE THREAD

**Issue by snobknob** [jdm-contrib/jdm#598]
# Backstory
I just visited the site, went to settings, then account, and there was an option to delete it.
Let me know if there's anything wrong with this submission, as I probably can help with more.

# Data

- `name`: mathway
- `url`: https://www.mathway.com/privacy
- `difficulty`: easy
- `notes`: Even though they state in their privacy policy that account deletion should be handled by contacting them, one can easily delete it by going into settings -> account.
- `domains`: https://www.mathway.com/Algebra

**Comment by jtagcat** [comment]
The sites, urls and additional notes are stored in [`_data/sites.json`](../blob/master/_data/sites.json).

Try editing it yourself. There's an edit button at the top (what actually forks (makes a copy) and edits your copy).

Other than following alphabetical order, a copy-pasta of an another entry should work.

After committing ('saving'), make a PR with a comment 'Closes #598'.

A few remarks:
 - URL should point to as close to the deletion page as possible (Something like https://www.mathway.com/settings/account maybe?).
 - Domains, not URLS, aka without the protocol (`https://`), skip the `www` subdomain and `Algebra` path. Giving you `mathway.com`.

If you get stuck, ask help here for any dumb reason.

**Comment by tupaschoal** [comment]
I found out that https://www.mathway.com/settings is the link to the deletion page. Filed a PR.

**Comment by jtagcat** [comment]
The comment looked so close to a PR, hoped we'd get somebody's hands making a comit.

**Comment by tupaschoal** [comment]
> The comment looked so close to a PR

That's the goal of the template!

> hoped we'd get somebody's hands making a commit.

I don't mind making the PRs every now and then. Every help counts, but some people aren't really accustomed to the whole git stuff, so it's alright

**Comment by snobknob** [comment]
> some people aren't really accustomed to the whole git stuff

Myself included! I'm new around. Now that I know how it works, I hope to contribute more in the future.
