### ISSUE TITLE
NextDNS

### ISSUE THREAD

**Issue by beerisgood** [jdm-contrib/jdm#599]
# Backstory

# Data

- [ ] `name`: 
- [ ] `url`: 
- [x] `difficulty`: easy
- [x] `notes`: account deletion is easy possible in account settings with clicking one button
- [ ] `email`: 
- [ ] `domains`:

**Comment by jtagcat** [comment]
Hi, could you please link to the deletion page?

A name of 'NextDNS' and domain of it would be needed as well. Probably something like NextDNS.org or NextDNS.com.

**Comment by beerisgood** [comment]
> Hi, could you please link to the deletion page?
> 
> A name of 'NextDNS' and domain of it would be needed as well. Probably something like NextDNS.org or NextDNS.com.

Sure:
URL is: https://my.nextdns.io/account
name: NextDNS
domain: https://nextdns.io/
