### ISSUE TITLE
Ebay update

### ISSUE THREAD

**Issue by karizma** [jdm-contrib/jdm#600]
# Backstory

I was trying to delete my ebay account

# Data

- [ ] `name`: 
- [x] `url`:  https://ocsnext.ebay.com/ocs/ca
- [x] `difficulty`:  hard
- [ ] `notes`: 
- [ ] `email`: 
- [ ] `domains`:

**Comment by jtagcat** [comment]
Hi, could you please add more details: What did you encounter (the process), did you need to email/chat with somebody? Did you get your account deleted?

**Comment by karizma** [comment]
Firstly needed to provide street address and a phone number (it was an alternative account before hand so I didn't have either of those yet), after adding those I either had to call them or email, since the account didn't have anything of value I just left it at that.

**Comment by tupaschoal** [comment]
Thanks for the clarification guys, looks like it's hard indeed.
