### ISSUE TITLE
Add Carbon Made

### ISSUE THREAD

**Issue by karizma** [jdm-contrib/jdm#601]
# Backstory

Going through my emails and deleting the accounts I found, one of them was carbonmade.

# Data

- `name`:  carbonmade
- `url`:  https://carbonmade.com/account/plan (need to be logged in for it to show)
- `url_CODE`: 
- `difficulty`:  easy

- `notes`: 
- `email`: 
- `email_subject`: 
- `email_body`: 
- `domains`:

**Comment by jtagcat** [comment]
Hi, is the name title case or all undercase?

**Comment by karizma** [comment]
Title case, "Carbonmade".
