### ISSUE TITLE
Adding one at a time or multiple

### ISSUE THREAD

**Issue by karizma** [jdm-contrib/jdm#606]
Currently I'm in the process of searching through my many email accounts and deleting accounts from sites I don't use anymore, I'm collecting the data of the process and want to add it to this repository. 

The data includes new sites, editing a few sites difficulty, and adding delete lag time (example: snapchat takes 30 days to delete)

1. Would it be preferable to add it as a pull request or as an issue?
2. Should I add them all in one pull request/issue

**Comment by tupaschoal** [comment]
> Would it be preferable to add it as a pull request or as an issue?

If you're comfortable in doing a PR, please do! It's preferred, but not everyone knows how to.

> Should I add them all in one pull request/issue

It's alright to do them in one PR, unless you have a crazy amount of changes/additions. Maybe split it into two: one for updating existing data, another for adding new ones.

**Comment by karizma** [comment]
Alright thanks, was planning on the split option like you suggested, looks like I'll go with that. Might take a few more days/weeks since I'm about 70-80% done.
