### ISSUE TITLE
Web form for submissions / edit proposals.

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#607]
re: few last issues

Should be an interesting thing to build (there probably is something out there) to compose a PR automagically. Editing is probably a bit more difficult.

I understand we don't have time, but I sometimes go wondering on random things, might do this in a few months.

**Comment by PyroSamurai** [comment]
This has been requested before and denied. https://github.com/jdm-contrib/jdm/issues/170
I'm pretty sure our stance is still the same on the subject.

**Comment by tupaschoal** [comment]
To be clear everyone kind of agreed there that it would be useful back then, we just weren't keen on pursuing it at the time (seemed hard to couple with our current architecture).

> Should be an interesting thing to build (there probably is something out there) to compose a PR automagically. Editing is probably a bit more difficult.

Should be interesting and entertaining indeed!

> I understand we don't have time

It's not only a matter of not having time, I think it's a bit of return on investment. The project requires very little maintenance today and it does receive its fair share of contributions every now and then.

I don't (and can't) know how much contribution would increase with such a solution, but If you want to pursue this for the sake of exploration and finding out more, I encourage you! If you find a solution (or possible one) with good compromise, we'll happily go over it and discuss.

**Comment by jtagcat** [comment]
Ah, didn't see the other issue, even using search.

It's a case of https://xkcd.com/1319/ and https://xkcd.com/1205/ and I know it's not really worth it.. ..

**Comment by tupaschoal** [comment]
Don't worry :)

**Comment by jtagcat** [comment]
(brain: so we just parse everything here to a database, then add the entry, then convert the database back to the source
.. wait, or just do some very ugly* bash)

(brain: live previews!, no registration, but wait it needs approval, ok then it needs an email / gh account if there are any comments; also we can link all site cards to the originating discussion)

(..or we could add a feature to rclone instead of writing this brain dump)
