### ISSUE TITLE
Udacity account deletions are now possible

### ISSUE THREAD

**Issue by macbrayne** [jdm-contrib/jdm#643]
# Backstory
As Udacity is quite a big company I found it a bit strange for the account to not be deletable according to JustDeleteMe so I checked their website for newer information.

# Data

- [ ] `name`: 
- [X] `url`: https://udacity.zendesk.com/hc/en-us/articles/360024003151-How-do-I-request-to-delete-my-account-
- [X] `difficulty`: medium
- [X] `notes`:  After logging in into your Udacity account and clicking on the button "Delete Your Data" under "Personal Information" you get sent a code by email to verify the deletion. Note that you are still being charged for any courses you are enrolled in!
- [ ] `email`: 
- [ ] `domains`:

**Comment by tupaschoal** [comment]
Thanks for reporting up-to-date information, I have updated accordingly!
