### ISSUE TITLE
Suggestion: Add default notes

### ISSUE THREAD

**Issue by kymckay** [jdm-contrib/jdm#653]
I think it might be a good improvement for the end user to have default notes instead of showing "no info available" when a `note` isn't provided (presumably when it's obvious what to do).

Perhaps something like "Visit the linked page and delete your account" if the difficulty is `easy` and "Visit the linked page for further information" otherwise. If an `email` is specified then there could be a default note indicating to either use the email link provided or manually write to `${address}`. This would also allow to cut down on translation for entries where a note is unnecessary.

**Comment by tupaschoal** [comment]
I like the suggestion! Shouldn't be difficult to implement, want to give it a try? :)

**Comment by SilentSpike** [comment]
I have a fair amount on at the moment, but will happily look at implementing this when I find some spare time (if nobody beats me to it) 😃

**Comment by AverageHelper** [comment]
The hardest part of this might be translation. I'd do it myself, but I'm only comfortable in a few languages using Google Translate for long phrases like this.

**Comment by tupaschoal** [comment]
We can always leave these untranslated and create an issue to ask for the community to complete the translation later :)

**Comment by kymckay** [comment]
Nice, glad someone was able to look at this :)

As a follow up suggestion: Reviewing existing `easy` entry notes to trim the fat from the translation workload for cases where the default message is good enough (probably the majority). I'll leave it up to you maintainers whether to open an issue task for that.

**Comment by tupaschoal** [comment]
> As a follow up suggestion: Reviewing existing `easy` entry notes to trim the fat from the translation workload for cases where the default message is good enough (probably the majority). I'll leave it up to you maintainers whether to open an issue task for that.

I gave this a thought and I'm alright with leaving as is, specially because we don't get a lot of translation movement around here.
