### ISSUE TITLE
Update Fitbit deletion instructions

### ISSUE THREAD

**Issue by kdkasad** [jdm-contrib/jdm#660]
# Backstory
As I was deleting my Fitbit acount, I noticed there is a way to do it from the website without contacting support.

# Data

- [ ] `name`: 
- [x] `url`: https://www.fitbit.com/settings/profile
- [x] `difficulty`: medium
- [x] `notes`: From the dashboard website, click Settings, then scroll down and click Delete Account.
- [ ] `email`: 
- [ ] `domains`:

**Comment by tupaschoal** [comment]
Thanks for the update, I've created #661 to apply the change.
Because it's just following a link and clicking a button, I'm actually updating it to easy. Let me know if you think it's more convoluted than that.

**Comment by kdkasad** [comment]
I had it at medium because clicking the button sends you an email which contains the link to actually delete your account.

I also just noticed that it says there's a 30-90 day wait until most of your data is actually deleted. I don't know if this would have any relevance.

**Comment by tupaschoal** [comment]
> I had it at medium because clicking the button sends you an email which contains the link to actually delete your account.

Hmm, that's relevant, I'll bump it up to medium then and add these to the notes

> I also just noticed that it says there's a 30-90 day wait until most of your data is actually deleted. I don't know if this would have any relevance.

I don't think so, lots of websites state that they take a bit longer, some for laziness, some for compliance with the law. As long as it's deleted, seems fine.
