### ISSUE TITLE
Obtain your data

### ISSUE THREAD

**Issue by daviddavo** [jdm-contrib/jdm#696]
Hello, I speak as a representative of a group of students from the Universidad Complutense de Madrid (UCM), Spain.

We wanted to make easier for people to exercise their right of access to personal data. Instead of starting from 0, we are creating a fork of your project that it's available at [repo](https://github.com/justgetmydata/jgmd), or [justgetmydata.com](https://justgetmydata.com/)

We wanted to ask the project if you could give us a few pointers and a bit of advice, and if you would accept a Pull Request with a button (or another kind of link or reference) to our project, Just Get My Data.

**Comment by tupaschoal** [comment]
Hello @daviddavo and fellow students of UCM!

First of all sorry for not replying earlier! I feel delighted that you've drawn inspiration from our project and are doing a spinoff with another very useful idea. In terms of tips, it's hard to say without a question, I think the repository is fairly easy to maintain and you got to be patient, for it won't grow out of nowhere.

As for the button, we don't mind having one on yours site to link to us and vice-versa. We won't promise that we'll keep it if we notice that the project has gone rogue or unmaintained.

 Let us know what you folks want to know

**Comment by daviddavo** [comment]
The question is, where should we put the link?

We have placed it in the header as another button, but tell us if you consider another place to put it.

**Comment by tupaschoal** [comment]
Let's discuss there how it looks
