### ISSUE TITLE
Update Evernote account process (you can now permanently close your account)

### ISSUE THREAD

**Issue by yukilikespie** [jdm-contrib/jdm#700]
# Backstory

I am deleting my evernote account, the jdm extension put me on deactivation page. I googled to see if I can permanently delete my Evernote account, and I found the help section where it says how you can delete it. I checked, you can, I deleted my account.

# Data

- [ ] `name`: Evernote
- [ ] `url`: https://help.evernote.com/hc/en-us/articles/360056549574-Permanently-close-your-Evernote-account
- [ ] `difficulty`: easy
- [ ] `notes`: You can now both deactivate and permanently delete your account
- [ ] `email`: 
- [ ] `domains`:

**Comment by tupaschoal** [comment]
Thanks for your contribution! I've already pushed the updated information
