### ISSUE TITLE
Make links more clear.

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#703]
Use either [![link](https://design.firefox.com/icons/icons/android/link-24.svg)](https://design.firefox.com/icons/viewer/#link) or [![share windows](https://design.firefox.com/icons/icons/desktop/share-16-windows.svg)](https://design.firefox.com/icons/viewer/#share%20windows) icon at the right of the link header (if link is available).

It might not be obvious to first time users, that there's a link to be used there.
(quick demo, icon should probably be more white, and smaller, and not aligned by hand)
![image](https://user-images.githubusercontent.com/38327267/103165011-4043f380-480a-11eb-9d5c-27c198f4bc82.png)

**Comment by tupaschoal** [comment]
Sounds like a good enhancement indeed

**Comment by PyroSamurai** [comment]
That's actually a pretty intuitive idea. I like the chain link better of those two options. You can probably just use a float within the div and just right-align it. You're linking it with the <a> tag via css, right?

**Comment by jtagcat** [comment]
I'd still keep the whole coloured header a link (`<a>`).

This supports clicking on the icon, clicking on the tet, and anything else new or returning visitors might click on.

**Comment by PyroSamurai** [comment]
yeah, I didn't suggest otherwise just using some img background css and align it right. You can make it a dynamic css class.
