### ISSUE TITLE
Lyft deletion process

### ISSUE THREAD

**Issue by chiraag-nataraj** [jdm-contrib/jdm#713]
# Backstory
After I saw that Uber was on JDM, I decided to look into Lyft's process.

# Data

- `name`: Lyft
- `url`: https://account.lyft.com/privacy/data
- `difficulty`: medium

- `notes`: Only can be done via the website, not the app
- `domains`: lyft.com,account.lyft.com

**Comment by tupaschoal** [comment]
I have just pushed this addition, thanks for your contribution!
