### ISSUE TITLE
OpenInvest deletion process

### ISSUE THREAD

**Issue by chiraag-nataraj** [jdm-contrib/jdm#714]
# Backstory
I saw that Acorns and Betterment were on JDM, so I figured I'd look into OpenInvest.
# Data

- `name`: OpenInvest
- `url`: https://www.openinvest.com/terms-of-service
- `difficulty`: hard

- `notes`: Email them telling them you want to delete your account. They will retain some information as necessary to "comply with our legal obligations, resolve disputes and enforce our agreements" (from their TOS and Privacy Policy), but most data will be deleted within 30 days.
- `email`: support@openinvest.com
- `domains`: openinvest.com,openinvest.co

**Comment by tupaschoal** [comment]
I have also just pushed this addition, thanks for your contribution!
