### ISSUE TITLE
Wish deletion instructions

### ISSUE THREAD

**Issue by chiraag-nataraj** [jdm-contrib/jdm#723]
# Backstory
I had created an account a while back and figured I should delete it since I don't use it anymore.

# Data

- `name`: Wish
- `url`: https://www.wish.com/settings/account
- `difficulty`: medium
- `notes`: You will have to edit your 'Country' in the profile to be a country covered by e.g. GDPR (for example, France). Otherwise, you will not see the 'Permanently delete account' option when you click on 'Manage Account' (you will only see 'Deactivate account').
- `domains`: https://www.wish.com

**Comment by tupaschoal** [comment]
Nice find about changing your country first!

**Comment by tupaschoal** [comment]
Thanks for your contribution!
