### ISSUE TITLE
Nextdoor information is not fully accurate

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/jdm#736]
# Backstory
While the information provided on their website appears to be accurate insofar as contacting support does cause your account to become disabled and removes your public posts, it does not seem to actually delete your account. This can be verified by attempting to log in with your old credentials--instead of getting a "Password incorrect" response, an email verification step is reached. (though no email appears to be sent--that is likely disabled on their end) I'm not sure whether this warrants changing the difficulty from "Hard" to "Impossible" for this entry.

**Comment by tupaschoal** [comment]
Hmm, difficulty indeed. How long has it been since you requested for deletion? Maybe we need to wait for like 15 or 30 days for complete purge? Some websites do it to comply with local laws

**Comment by Nightfirecat** [comment]
I suppose that's true. Sadly I won't be able to check as I've already purged my password manager of my old credentials there. (meant to move it to the "Recycle Bin" folder, oops)
This is probably fine where it's at now.
