### ISSUE TITLE
Update Nexus Mods

### ISSUE THREAD

**Issue by Pickysaurus** [jdm-contrib/jdm#738]
# Backstory
I am a Community Manager at Nexus Mods and I have noticed that data you show for our service is incorrect. 

# Data

- [ ] `name`: Nexus Mods
- [ ] `url`: https://nexusmods.com
- [ ] `difficulty`: Easy
- [ ] `notes`: Accounts can be permanently deleted by the user: https://help.nexusmods.com/article/25-how-do-i-delete-my-account
- [ ] `email`: support@nexusmods.com
- [ ] `domains`: *.nexusmods.com/

**Comment by tupaschoal** [comment]
Thanks for providing the most up to date information! I just opened #739 to change it. I didn't add the e-mail because from the link you provided, it seems like there is no need to contact support, is there?

**Comment by Pickysaurus** [comment]
Thanks for the rapid response. You are correct, there isn't any reason to contact support to complete this process. The only instance where they may need to is if they are having some kind of issue.

**Comment by tupaschoal** [comment]
Great, than we're all set :)
