### ISSUE TITLE
Discord does not delete messages upon account deletion

### ISSUE THREAD

**Issue by IFoundAnotherUsername** [jdm-contrib/jdm#749]
# Backstory
Upon [asking discord staff](https://support.discord.com/hc/de/requests/new) the following questions about their account deletion process,
> Do my data get deleted (erased) permanently 14 days after deleting my account, including backups or any other storages (including those out of control of discord)?
> How long do you keep a copy of my data after deletion, if not 14 days?
> Also: Will deleting a single message lead to it being erased permanently on all storages, including backups and storages out of control of discord?

I got the following reply:
> I understand the process could be a bit confusing, I'm here to guide you through it! Just to let you know, the deletion process can take up to 15 days to complete, which is why an account will still appear active.
> I say 15 days just in case since this is the average period of time it takes for our system to fully process an account deletion. However, if you see that your account is still active after 15 days, you can let us know and we'll escalate this to our team to investigate further.
> Note: Account removal does not remove anything beyond the account itself (avatar, username, and email address), while text and strings from previous conversations will still exist unless manually deleted.
> Additionally, if you wish to use the email associated with the account that you're deleting, you would have to wait until the account has been fully removed, and the email becomes usable again.
> Hope that helps! If you have any other questions, please let me know.

So now we know account deletion is not data deletion, which leads to the following changes:

# Data
- [ ] `url`: "discordapp.com", "discord.com"
- [ ] `difficulty`: medium
- [ ] `notes`:  Account deletion will not delete your messages, which you must do manually (Automating this process is possible using projects such as [Undiscord](https://github.com/victornpb/deleteDiscordMessages)). If you're a server owner, you'll need to either [delete the server](https://support.discordapp.com/hc/en-us/articles/213595197-How-do-I-delete-a-server-), or [transfer ownership](https://support.discordapp.com/hc/en-us/articles/216273938-How-do-I-transfer-server-ownership-) for account deletion to succeed. Account deletion takes 15 days on average (You can restore your account in this time).

Is this note too long? If so maybe the 15 days comment is not necessary.

(Beneath that I also added the domain discord.com as it evidently is now the main page discord uses instead of discordapp.com.)

# Contributing.md
Furthermore I suggest the following changes to CONTRIBUTING.md, **if it is not blowing up the guidelines**
- [ ] Add a paragraph about whether to delete translations of changed deletion procedures (Such as in this case the turkish and italian translations of the discord procedure).
- [ ] Add a rule on whether (or when) to link independent deletion programs (Such as in this case [Undiscord](https://github.com/victornpb/deleteDiscordMessages)) to CONTRIBUTING.md.

**Comment by tupaschoal** [comment]
Thanks for the update on Discord!

> Is this note too long?

No, it's fine, of course we don't want lots of paragraphs, but we do strive to provide the best information possible.

> Add a paragraph about whether to delete translations of changed deletion procedures (Such as in this case the turkish and italian translations of the discord procedure).

Will do. We suggest people to delete translations when they are changing the notes drastically, unless they also speak some of the languages mentioned.

> Add a rule on whether (or when) to link independent deletion programs (Such as in this case Undiscord) to CONTRIBUTING.md.

I think this is too specific (hasn't happened yet for all the entries we already have?) So I'd rather treat it case by case. I did add the mention to Undiscord, but I didn't mention to it, as I don't think we want to refer people to other services we didn't test, I hope you understand!
