### ISSUE TITLE
Hi-Rez Studios account can be deleted

### ISSUE THREAD

**Issue by SuperSamus** [jdm-contrib/jdm#754]
# Data

- [ ] `name`: Hi-Rez Studios
- [ ] `url`: https://my.hirezstudios.com/security
- [ ] `difficulty`: hard
- [ ] `notes`: Go to https://my.hirezstudios.com/security, make sure the email address is verified, on the Security Tab click "CLICK HERE TO REQUEST AN ACCOUNT DELETION OR MAKE AN ACCOUNT DATA REQUEST", follow the steps.

**Comment by tupaschoal** [comment]
Thanks for your contribution!

**Comment by SuperSamus** [comment]
It seems they have changed it, the instructions here are now obsolete.
https://hirezstudios.zendesk.com/hc/en-us/articles/13824369999380-Deleting-Your-Account-or-Requesting-Account-Data
I don't want to delete it, so I can't test any of that.
