### ISSUE TITLE
FB Messenger messages.

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#756]
You can now unsend-for-everyone all of _your_ messages.
I'm not certain, if unsent for everyone messages get actually deleted on fb (likely not).

Anyway, https://github.com/theahura/shoot-the-messenger is a thing, but it didn't work well for me. I wrote a quick AutoHotKey script, combined with uBlock (uBlock to remove images, embeds, stopping AHK clicking them; also one side's (your vs other ppl) messages at a time. AHK script clicked on the first message, then proceeded with tab tab space left right left right madness.

***

Also as a warning, deleting a conversation is just hiding the messages, with no way back.

**Comment by tupaschoal** [comment]
Interesting stuff, though it is not clear to me what action you want us to take. We could have an entry for FB messenger on the website, though recently I said that I don't want to recommend other 3rd party software to the users, as we can't make sure they're also doing the right thing.

**Comment by jtagcat** [comment]
Broadening the discussion, there's probably more dependency/partnership services.

The best example is the Facbook-Instagram-Whatsapp-Messenger etc thing, where to delete your data:
 - You can't delete them from the parent service, have to do it from the child, maybe even in particular order.
 - One service is tightly integrated with another (essentially one service under 2 names), if you want your data deleted, you have to delete all the integrated services.

***

Though yes, I don't have an idea on how to handle this as well, other than having a long list of warnings (probably deserving a blog post rather than a very long note).

**Comment by tupaschoal** [comment]
I really encourage the blog post, if you need help reviewing, let me know!
As for an AI on the repo itself, I don't see how we can act, so I'll close the issue, sorry...
