### ISSUE TITLE
Roblox has Incorrect Listing

### ISSUE THREAD

**Issue by ColeSquared** [jdm-contrib/jdm#813]
# Backstory
I often use the Roblox platform. 

# Data

- [ ] `name`: Roblox
- [ ] `url`: https://en.help.roblox.com/hc/en-us/articles/203313050-How-Do-I-Delete-My-Account-
- [x] `difficulty`: hard
- [x] `notes`: Have to live in a place with legal regulations to delete account. 
- [x] `email`: https://roblox.com/support
- [ ] `domains`: https://www.roblox.com/

**Comment by tupaschoal** [comment]
Tended to on #814
