### ISSUE TITLE
4PDA account remove

### ISSUE THREAD

**Issue by rsprolo** [jdm-contrib/jdm#818]
# Backstory
Once I needed to delete an account there, but I could not. 

name - 4PDA
url - does not exist
difficulty - impossible
domains - 4pda.ru, 4pda.to

**Comment by tupaschoal** [comment]
What do you mean by the "URL does not exist"? We need at least the url of the website even if it isn't the deletion URL

**Comment by rsprolo** [comment]
ok, site is 4pda.ru (redirect to 4pda.to, because blocked by RKN, temporarily)

**Comment by rsprolo** [comment]
broken url https://justdeleteme.xyz/4pda.ru instead of 4pda.ru / 4pda.to

**Comment by tupaschoal** [comment]
Thanks for checking, fixed on https://github.com/jdm-contrib/jdm/commit/45e41848ba1112cffe56c290cec400c366c6bed2
