### ISSUE TITLE
blackspigot account remove

### ISSUE THREAD

**Issue by rsprolo** [jdm-contrib/jdm#820]
# Backstory
I am trying to remove that, but this impossible

# Data

name - blackspigot
url - blackspigot.com
difficulty - impossible
notes: 
https://blackspigot.com/threads/delete-account.9291/
    We do not offer account removals.

    THREAD LOCKED!
   
XDhunterXD, May 21, 2020 

domains: blackspigot.com

**Comment by tupaschoal** [comment]
Closed by #823
