### ISSUE TITLE
FL.ru account remove

### ISSUE THREAD

**Issue by rsprolo** [jdm-contrib/jdm#829]
# Backstory

# Data

- `name`:  FL.ru
- `url`:  fl.ru/users/your_id/setup/delete/
- `difficulty`: 
 easy

- `notes`:  you must stay you profile id to link 

- `domains`:  fl.ru

**Comment by tupaschoal** [comment]
Does `your_id` on the link (`fl.ru/users/your_id/setup/delete/`) change to the person actual username? Or is the link like this?

If it's the former then we better use a generic link and explain on the notes, if it's the latter, then it's ok.

**Comment by rsprolo** [comment]
No, you have to paste your url into this link, otherwise it won't work

**Comment by tupaschoal** [comment]
Then can you describe how to get to the deletion page or button? We don't want to paste invalid links on the URL, because people that would just click would think it's broken.

**Comment by rsprolo** [comment]
I forgot
