### ISSUE TITLE
Translate notes to russian 

### ISSUE THREAD

**Issue by rsprolo** [jdm-contrib/jdm#832]
# Backstory
 I can translate that

# Name of service: translate
Amazon: 
Прокрутите вниз, выберите причину, отметьте флажок «Закрыть мою учетную запись» и следуйте ссылке в электронной почте подтверждения. 

Blogger:
Вы не можете удалить учетную запись Blogger без удаления всей учетной записи Google. Но вы можете удалить свой блог. 

eBay:
До удаления учетной записи вам будут заданы несколько вопросов.

Facebook:
Хотя вы можете легко удалить свой аккаунт, некоторые данные, включая сообщения, останутся навсегда, это указано в политике конфиденциальности веб-сайта.  

GoDaddy:
Перейдите к настройкам учетных записей, выберите «Закрыть учетную запись» и подтвердите. 

Groupon:
Согласно заявлению конфиденциальности Groupon, вам необходимо напрямую связаться с поддержкой и попросить их удалить свою учетную запись. 

LinkedIn:
Есть сообщения, которые LinkedIn продолжают присылать по электронной почте людям с закрытой учетной записью. Возможно, вам придется связаться с службой поддержки для удаления учетной записи вместо закрытия.

Match:
Вы можете только деактивировать свой аккаунт .

 Netflix:
Отмените свое членство, затем обратитесь в службу поддержки, если вы хотите немедленное удаление, в ином случае ваша учетная запись будет автоматически удалена через 10 месяцев. 

Pinterest:
В настройках учетной записи нажмите «Удалить учетную запись», выберите причину и нажмите «Далее», затем «отправить электронную почту». Вам нужно будет проверить электронную почту и подтвердить удаление. 

Reddit:
Вы не можете удалить свою учетную запись Reddit; Вы можете только деактивировать ее. Данные, размещенные на Reddit (посты и комментарии), должны быть удалены вами заранее. Если вы являетесь гражданином ЕС, см. Reddit (GDPR) на JustDeleteMe. 

Reddit (GDPR):
Данные, размещенные на Reddit (посты и комментарии), должны быть удалены вами заранее. Как гражданин ЕС, не используйте стандартный процесс деактивации. Вместо этого отправьте сообщение с предоставленной ссылкой. 

Skype:
Свяжитесь со службой поддержки в чате. Вам необходимо проверить, купили ли вы услуги из Skype, а также вам нужно будет подтвердить ваш указанный адрес электронной почты. 

Stripe:
Только владельцы аккаунта, а не члены команды могут удалить вашу учетную запись. Остатки и незавершенные счета  должны быть разрешены до того, как учетная запись будет навсегда закрыта. Не может быть отменено. 

Twitter:
Ваша учетная запись деактивируется перед удалением. После деактивированных 30 дней, он будет удален. 

Wikipedia:
«Имя пользователя не может быть удалено». Однако у них есть несколько предложений. 

WordPress.com:
Вы можете навсегда закрыть свою учетную запись WordPress.com с экрана настроек вашей учетной записи, нажав на «Закрыть учетную запись навсегда» 

YouTube:
Вы можете запросить копию данных перед удалением учетной записи YouTube. 

It is "popular". Other, may be, later

**Comment by tupaschoal** [comment]
Thanks, I've just incorporated them :)
