### ISSUE TITLE
Translate notes on 'A' to russian

### ISSUE THREAD

**Issue by ghost** [jdm-contrib/jdm#836]
# Backstory
I thought to translate everything, but there are a lot of them 

# Name of service: translated
/e/:
Профиль > настройки > удалить аккаунт > подтвердить.

000Webhost:
Перейдите в Профиль > «Удалить мою учетную запись» и выберите, почему вы удаляете свою учетную запись. 

123RF:
Единственный способ удалить учетную запись - отправить электронное письмо службе поддержки. 

1Password:
Войдите в свою учетную запись, перейдите в профиль, нажмите «Удалить учетную запись навсегда». Подтвердите, введя «Я уверен» и нажав «Удалить учетную запись». 

280Daily:
Введите пароль от своей учетной записи и нажмите «УДАЛИТЬ УЧЕТНУЮ ЗАПИСЬ».

500px:
В настройках учетной записи в разделе «Выберите проблему ниже» выберите «Удалить учетную запись», заполните форму и отправьте. 

7digital:
Отправьте электронное письмо в службу поддержки, используя контактную форму в Интернете, и попросите удалить вашу учетную запись.  

99designs:
Свяжитесь с ними, они только попроят подтверждения.

9GAG:
Войдите в свою учетную запись, перейдите в параметры, нажмите «Удалить мою учетную запись». Подтвердите, нажав «Я хочу удалить свою учетную запись» и снова нажав «Удалить мою учетную запись 9GAG». 

Abacashi:
Используйте контактную форму, или отправьте электронное письмо напрямую с просьбой удалить учетную запись. 

AbeBooks:
Выберите «Что-то еще», затем «Закрыть мою учетную запись» и заполните форму электронной почты. 

Acasa:
В настройках вашей учетной записи выберите снизу «Удалить мою учетную запись». 

Acorns:
Вам необходимо связаться со службой поддержки, чтобы деактивировать свою учетную запись. Может быть снова активирована. 

ActiveCampaign:
Для запроса на удаление учетной записи или запроса на удаление всей информации учетной записи отправьте форму запроса прав субъекта данных. На вопрос: «Что бы вы хотели принять с нами?» выберите вариант «Я хочу, чтобы меня забыли, и хочу, чтобы мои личные данные были удалены». 

Ada:
Нажмите "Удалить", и все данные вашей учетной записи будут удалены. 

Adafruit:
Нажмите «Удалить» и подтвердите.

Adfly:
Свяжитесь со службой поддержки, используя контактную форму, и запросите удаление вашей учетной записи. 

AdvCash:
Перейдите на страницу профиля и нажмите кнопку «Удалить», чтобы удалить аккаунт.  

Airbnb:
Вашу учетную запись можно удалить, обратившись в службу поддержки, однако некоторая важная информация может быть сохранена в соответствии с требованиями закона. 

Airdroid:
Перейдите на страницу информации об учетной записи, нажмите кнопку «Удалить учетную запись», чтобы удалить свою учетную запись AirDroid. 

Alibaba:
Чтобы удалить свою учетную запись, перейдите на страницу «Моя учетная запись», нажмите «Профиль участника», а затем «Деактивировать учетную запись». 

Aliexpress:
Чтобы удалить свою учетную запись, перейдите на страницу «Мой AliExpress», нажмите «Настройки учетной записи» -> «Изменить настройки», затем «Изменить профиль участника» и нажмите кнопку «Деактивировать учетную запись». На странице деактивации есть опция «Освободить мою учетную запись в то же время», щелкните ее и подтвердите, чтобы данные были окончательно удалены вместе с вашей учетной записью. 

AllCall Forum:
Веб-сайт не предлагает никаких опций, позволяющих удалить учетную запись. 

Alvanista:
Перейдите по ссылке, чтобы отредактировать свой профиль, и нажмите внизу отменить учетную запись. 

Amara:
Просто перейдите на страницу учетной записи и нажмите красную кнопку «Удалить учетную запись» в левом нижнем углу страницы. 

Amazon AWS:
Вы должны войти перед переходом по ссылке. 

Android File Host (AFH):
Свяжитесь со службой поддержки клиентов, используя контактную форму, и запросите удаление вашей учетной записи. 

Angelist:
После входа, нажмите «Удалить учетную запись». 

AniList:
Перейдите к «Удалить учетную запись пользователя > ОК, Удалить мою учетную запись». 

Animal Crossing Community:
Мы не «удаляем» и не «закрываем» учетные записи на ACC. Если вы больше не хотите использовать сайт, вы можете удалить всю личную информацию из своего профиля, а затем прекратить заходить на учетную запись. 

Animoto:
Откройте ссылку и нажмите «Удалить учетную запись». 

AnkiApp:
Войдите в свою учетную запись и нажмите «Удалить учетную запись». Подтвердите ввод пароля и нажмите «ОК». Если вы не можете удалить свою учетную запись через web.ankiapp.com - посетите join.ankiapp.com. 

AnkiWeb:
Подтвердите, введя свой адрес электронной почты и нажмите «Удалить».

AnonAddy:
Введите пароль и внизу страницы нажмите «Удалить учетную запись». 

Any.do:
Вы можете удалить свою учетную запись только через мобильное приложение: установите приложение, войдите в систему, нажмите «Профиль», затем «Удалить учетную запись». 

Apex Minecraft Hosting:
Вам необходимо войти в свою биллинговую панель и отправить заявку на удаление учетной записи. Если у вас только  «multicraft account», вы можете отправить тикет без входа в систему. 

AppFog:
Удалите все приложения и службы из своей учетной записи, а затем запросите удаление, отправив электронное письмо в службу поддержки. 

Apple:
Следуйте инструкциям, чтобы запросить удаление учетной записи. Отменить можно за несколько дней. 

AppShoper:
Чтобы запросить удаление учетной записи, вы должны написать на электронную почту: support@appshopper.com

The Artist Union:
Сначала войдите в свою учетную запись. Нажмите «Удалить учетную запись» и подтвердите, нажав «ОК».  

Asgardia.space:
Вам необходимо отправить электронное письмо и запросить удаление учетной записи, что может занять до 10 дней. В некоторых учетных записях администраторы сайта не отслеживают запросы на удаление, что не приводит к последующим действиям. 

Asos:
Запросить удаление из службы поддержки. 

Audiomack:
Щелкните на ссылку удаления учетной записи в левом нижнем углу. 

Autodesk:
Внизу страницы нажмите кнопку «Удаление учетной записи» и подтвердите «Удалить свою учетную запись и данные Autodesk». Введите свой пароль, затем введите 6-значный код, который будет отправлен на вашу электронную почту, и нажмите «Удалить учетную запись». Вы можете восстановить учетную запись в течение 30 дней после ее удаления. Удаление завершается через 90 дней. 

Avast!:
Войдите в систему, перейдите на вкладку «Детали профиля» и нажмите кнопку «Удалить учетную запись». 

Avira:
Следуйте инструкциям, приведенным в статье. При желании вы также можете запросить удаление своей учетной записи по электронной почте. 

AwardWallet:
Вы должны ввести свой пароль и указать причину удаления вашей учетной записи.

**Comment by tupaschoal** [comment]
Hello @rsprolo,

Thanks for your continued contributions, I was wondering if you could try proposing the changes yourself? That would make it a lot faster to review & merge the new additions and translations and it's very easy to do via GitHub's web interface, you don't need to know a thing about programming.

Just head over to the file [sites.json](https://github.com/jdm-contrib/jdm/blob/master/_data/sites.json) and click the pencil icon there to start editing:
![image](https://user-images.githubusercontent.com/6443427/119343986-8001f080-bc6d-11eb-9b52-99a128ddae07.png)

When you're done, there'll be a big green button to submit a pull request for us :)

**Comment by rsprolo** [comment]
OK I'll try

**Comment by rsprolo** [comment]
run it if you want, i am tried to fix that, sorry

#  start
import json


problems = 0
file1 = open('fewdata', encoding='utf-8').read()  #fewdata is my file with rus translate
temp = file1.split('\n\n')
file2 = open('sites.json', encoding='utf-8') 
new = json.load(file2)
for i in range(len(temp)):
    if "notes" in new[i]:
        new[i]["notes_ru"] = temp[i - costyli].split("\n")[1]
    else:
        problems += 1
        

with open('end.json', 'w') as file:
    json.dump(new, file, indent=4, ensure_ascii=False)
#  end

**Comment by Spectroxx** [comment]
Solved in #884 
Can close this now.
