### ISSUE TITLE
🤔 Suggestion: Add an OpenSearch description file

### ISSUE THREAD

**Issue by ZER0-X** [jdm-contrib/jdm#917]
By adding OpenSearch description the browser will treat the site as a search engine, so we do not have to open the site to search for a service, but doing it directly from the browser's search bar.
_Rather then saving the website as a bookmark i woud like to have it directly in the browser's search bar._

When the site has an OpenSearch description, you will get a button in the browser to add it as a search engine so you can use it when ever you want by type some thing to the search bar then click on the website's favicon.
Also you can have some search suggestions, although it only works with Firefox.

It shoud be very easy to implement sinse the search functionality uses the url `https://justdeleteme.xyz/#{searchTerms}`

[This is a documentation in MDN.](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)
[This is a documentation in the GitHub repository.](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md)

# Those are some examples:
### Google Translate
https://translate.google.com/opensearch.xml
### DuckDuckGo
https://duckduckgo.com/opensearch.xml
### StackOverFlow
https://stackoverflow.com/opensearch.xml
### GitHub
https://github.com/opensearch.xml

**Comment by PyroSamurai** [comment]
Do people really visit our site so often that they have to think of it as a search engine? They must be creating accounts just to delete them for fun if that is the case.

**Comment by tupaschoal** [comment]
Though not visiting often, whenever I think about searching I try tab-bing so I think it would be neat if it works

**Comment by Nightfirecat** [comment]
This seems like a pretty low-cost effort, so I don't see a reason we couldn't add it.
