### ISSUE TITLE
Change formatting of SupportedLanguageKeys

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#927]
The SupportedLanguageKeys list on the script below is very large and everytime a new key is added, it requires a painful reorder. Changing it to 1 per line, though it will take more real estate, will make it much easier to modify in the future.

https://github.com/jdm-contrib/jdm/blob/36e727151bfb5c5e98f68633aed5266f1eb9f369/script/validate_json.rb#L25-L31

**Comment by Nightfirecat** [comment]
For what it's worth, most IDEs offer support for collapsing array definitions, so this is unlikely to cause any significant impact to developers.
