### ISSUE TITLE
Several newer repository files are copied to main site which should not be

### ISSUE THREAD

**Issue by Nightfirecat** [jdm-contrib/jdm#931]
[The `exclude` directive of our Jekyll config](https://github.com/jdm-contrib/jdm/blob/00e668f616fc5d752de9907228d3517ac2f63ca7/_config.yml#L1) currently does not include several repository files which have been added more recently, such as `CNAME` and `TRANSLATION_REFERENCE.md`, meaning that they can be accessed and downloaded by visiting https://justdeleteme.xyz/CNAME or https://justdeleteme.xyz/TRANSLATION_REFERENCE.md. While this isn't security-critical, there's no need for us to serve these files on the web server, so these (and any other new files) should be excluded.

**Comment by tupaschoal** [comment]
Nice catch!
