### ISSUE TITLE
Inconsistent ISO Codes

### ISSUE THREAD

**Issue by Foggalong** [jdm-contrib/jdm#941]
While digging around for #940 I found this very minor and very nerdy issue; the [translation docs](https://github.com/jdm-contrib/jdm/blob/master/CONTRIBUTING.md#translation) say `CODE` should be the 'short country code' but the actual values are a hodgepodge of four different systems (something again just inherited from the original project).

- Most are [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes, like `sr` for Serbian (whose country code is `rs`) or `ar` for Arabic (whose country code is `ma`). 
- A few are [ISO 3166-1 Alpha-2](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) country codes, like `cz` for Czechia (whose language code is `cs`) or `kr` for South Korea (Korean's language code is `ko`). 
- Three use [ISO/IEC 15897](https://en.wikipedia.org/wiki/ISO/IEC_15897) locale codes to denote country-specific language variants: `pt_br`, `zh-cn`, and `zh-tw` (though not consistently, e.g. `en_gb` or `ko-kr`).\* To complicate further, the filenames for these are _just_ the 639-1 codes.
- Out there on its own, Catalan uses `cat` which is an [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) code; the 639-1 code is `ca` and its [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:ES) sub-division code is `es-ct`.\*\*

None of the current translations clash, but it could happen if someone were to submit Argentine Spanish, Canadian French or English, anything from Suriname, etc. If it doesn't otherwise cause issues, I'd suggest maybe moving over to a locale-based coding system (epecially if it were being looked at as part of #503) but either way the documentation needs updating to reflect what option people should actually be using.

**Comment by Foggalong** [comment]
Weird bonus facts I learned researching this:

\* The 15897 codes are essentially 3166-1 codes appended to 639-1 codes, and then the POSIX implementation of the standard uses `_` while the Windows implementation uses `-` (where they're known as LCID codes). I kinda feel like the delimiter is a feature that should have been part of the ISO standard, but maybe that's just me :sweat_smile: 

\*\* The subdivision code for Catalonia is `es-ct` and its locale is `ca-es`, but in some places online one or the other is erroneously given as `es-ca`; that's actually the 3166-2 code for [Cádiz](https://en.wikipedia.org/wiki/Province_of_C%C3%A1diz) at the opposite end of Spain.

**Comment by tupaschoal** [comment]
Thanks for the great investigation. I remember something like this was an issue back when #503 was being developed indeed, but as it never got finished, we never followed up either. I'm not sure I get the direction you're suggesting us to move to, though, but again I'm no expert in the mess that these language codes are.

**Comment by Foggalong** [comment]
Since it's languages I think using locale (ISO/IEC 15897) is the safest bet - idk how likely is that there'll be a flurry of translations in the future but it's good practice future proofing wise

**Comment by Foggalong** [comment]
If you want to use a standard then since it's languages using one of the two language based standards, 693-2 or 15897, would be the best bet; I don't know how likely it is there'd be a sudden influx of translations but those would be best for really future proofing.

Honestly though, as you say, having a consistent system is the most important thing. Even if it's just [grabbing a complete list of locales](https://gist.github.com/jacobbubu/1836273) from somewhere else and using that as the reference for translators would help remove the inconsistency.

**Comment by Kefaku** [comment]
I propose using language tags [as described by the IETF in BCP47](https://www.rfc-editor.org/rfc/rfc5646.html).

In our case, that would mean using the shortest available [ISO 639 code](https://www.loc.gov/standards/iso639-2/php/English_list.php) and appending an [ISO 3166-1 alpha-2 ](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) country code using a hyphen to distinguish the region, if necessary.

For example:
* `cs` for Czech
* `pt-PT` for portuguese as spoken in Portugal

(if more precision is needed in the future BCP47 allows for script/variant to be included in the language tag)

This would allow us to standardize with only minimal changes. And as @tupaschoal desired, reliable lists for both parts are available.

If approved, I would be willing to implement these changes.

**Comment by tupaschoal** [comment]
Go for it @Kefaku . It would also simplify our https://github.com/jdm-contrib/jdm/blob/master/crowdin.yml file, given that it currently has to work around inconsistent codes.
