### ISSUE TITLE
UPDATE: Rotten Tomatoes no longer that easy...

### ISSUE THREAD

**Issue by Nachtalb** [jdm-contrib/jdm#978]
## Backstory

Well... the Provided link does not work anymore. Thus I googled for a new way. 

## Data

- [ ] `name`: Rotten Tomatoes
- [ ] `url`: https://support.fandango.com/contact/contact-us-fandango-rkksORSDO?from=RT
- [ ] `difficulty`: hard
- [ ] `notes`: If you want to delete an account you’ve created on Rotten Tomatoes, please contact an agent on live chat or fill out the email contact form. 
- [ ] `email`: -
- [ ] `domains`: -

**Comment by tupaschoal** [comment]
Oh, it's sad to see when it gets worse :(
