### ISSUE TITLE
Improve alignment of language icon

### ISSUE THREAD

**Issue by tupaschoal** [jdm-contrib/jdm#983]
@Foggalong removed the country flags and introduced the language icon on #943. There is a small alignment improvement that can still be made. The icon and the "About" text are aligned by their bottom parts, but it would look neater (I guess) if their centers aligned, see how it looks today:

![image](https://user-images.githubusercontent.com/6443427/139746620-92104b82-0df1-455e-a7fe-4747b3c76f13.png)

Task is just to slightly improve this alignment.

**Comment by Nightfirecat** [comment]
Setting `vertical-align: middle;` on each of the `<a>` children of `<nav>` seems to fix this nicely.

**Comment by PyroSamurai** [comment]
we add it to the style.css in the "nav a" blocks then.
