### ISSUE TITLE
JDM Listings broken on main page.

### ISSUE THREAD

**Issue by Spectroxx** [jdm-contrib/jdm#985]
### STEPS TO REPRODUCE BUG

-  Open [JDM](https://justdeleteme.xyz/) on firefox or chrome
- Scroll down where the websites start in "FL"

**BUG**
Notice the listings are in one row instead of 4
Images of the bug Chrome 95 [BUG](https://cdn.discordapp.com/attachments/808095672393924618/907711933682184282/unknown.png) Firefox 94 [BUG](https://cdn.discordapp.com/attachments/808095672393924618/907712308640350208/unknown.png)

![](https://cdn.discordapp.com/attachments/808095672393924618/907719244744097792/PZeooFgdrP.gif)

Both browsers give the same result.

Yet to check what is the cause. Let me know if anyone can reproduce this.

**Comment by Nightfirecat** [comment]
The issue is that the markup for the Fiverr entry is wrong: https://github.com/jdm-contrib/jdm/blob/772e3952e6ce46e57bdc528816c8f4f4d904d254/_data/sites.json#L3699

It needs to be changed like below:
```diff
- For each checkbox, choose: <ul><li><strong>Category:<strong> \"Data and privacy\"</li><li><strong>Topic:<strong> \"Permanently delete my personal data\"</li><br>Click on the little link \"here\" under the light blue box. Fill the fields and submit request, soon, an account manager will answer you and process your request.
+ For each checkbox, choose: <ul><li><strong>Category:</strong> \"Data and privacy\"</li><li><strong>Topic:</strong> \"Permanently delete my personal data\"</li><br>Click on the little link \"here\" under the light blue box. Fill the fields and submit request, soon, an account manager will answer you and process your request.
```
