### ISSUE TITLE
ADD: LogMeIn / Hamachi

### ISSUE THREAD

**Issue by Nachtalb** [jdm-contrib/jdm#990]
## Data

- `name`: LogMeIn / Hamachi
- `url`: https://support.logmeininc.com/hamachi/help/how-do-i-contact-hamachi-customer-support
- `difficulty`: hard
- `notes`: Scroll to the bottom of the given URL and open a new ticket and ask for account deletion. 
- `domains`: logme.in, logmeininc.com, logmein.com

**Comment by lucasew** [comment]
I didn't have confirmation about the process but it seems that now they have a form that one can request account deletion. I did. They give a deadline of 15 days to react.

https://submit-irm.trustarc.com/services/validation/818563f9-8d9c-4029-880a-bc743fb49de5

**Comment by tupaschoal** [comment]
Let us know if you receive a reply in 15d or less.

**Comment by lucasew** [comment]
![Screenshot_20240617-103914](https://github.com/jdm-contrib/jdm/assets/15693688/3bb81010-0772-40f6-a8b4-036936cd9a26)

Account is not logging in anymore,  it seems it's gone \o/

**Comment by tupaschoal** [comment]
Nice, I've updated the information, thanks for the help @lucasew
