### ISSUE TITLE
ADD: Teespring

### ISSUE THREAD

**Issue by Nachtalb** [jdm-contrib/jdm#992]
## Data

- `name`: Teespring
- `difficulty`: hard
- `email`: privacy@teespring.com
- `email_subject`: Delete Account Request
- `email_body`: Please delete the account associated with this email address.
- `domains`: teespring.com

**Comment by SvicidalBug** [comment]
There needs to be a `url` with this.
Do they have a support article saying they accept deletion requests at that address? If not, their privacy policy may be acceptable.

**Comment by Nachtalb** [comment]
The thing is I have not found any official sources, though the common consensus when searching for a solution on Google is to use said email above. Eg. https://libreddit.s.nachtalb.io/r/Teespring/comments/fdmzn5/close_storedelete_account/

**Comment by SvicidalBug** [comment]
I've sent them an email asking for clarification. If I don't get a response in a few days, Ill try again with the email address they have in their privacy policy (privacy@spri.ng).

**Comment by Nachtalb** [comment]
Ahh, thanks for the proactive investigation! 👍

**Comment by SvicidalBug** [comment]
After 5 days, I haven't received a response from either `privacy@teespring.com` or `privacy@spri.ng`.

I'm not sure what to do here. Maybe it could be added as `impossible` for now along with their email and a note encouraging to try emailing a request anyway. Something like:
`"notes":  "It's currently unknown if they allow account deletions, but you can try emailing and asking. Do share their response with us on GitHub!"`
Could include a hyperlink to this issue in there.

What do you think, @tupaschoal?

**Comment by tupaschoal** [comment]
I think 5d is relatively too soon, I'd say if you don't hear back from then in two weeks, then we can add it as impossible.

**Comment by tupaschoal** [comment]
@SvicidalBug if you haven't heard back from them by now, I think it's safe to list it as impossible.
